### ISSUE TITLE
Issue running RF Pipe Sample (#6)

### ISSUE THREAD

**Issue by trentbottin** [coreemu/core#114]
I just performed a clean install of EMANE (v1.0.1) and Core (v4.8) on Ubuntu 14.04 using pre-built packages; no issues during installation and no configs were modified.  When I attempted to run the samples provided to test functionality, the RF Pipe sample hung up (output from the core-daemon log provided below).  I also tried a smaller network with just two nodes and observed the same behavior.

SESSION 41946 STATE 3: INSTANTIATION at Thu Mar 23 08:27:53 2017
Setup EMANE with master=True.
Thread-825: exception while handling msg:
CoreEventMessage <msgtype = CORE_API_EVENT_MSG, flags = 0x0 <>>
  CORE_TLV_EVENT_TYPE: 3
Traceback (most recent call last):
  File "/usr/sbin/core-daemon", line 292, in handlemsg
    replies = msghandler(msg)
  File "/usr/sbin/core-daemon", line 1112, in handleeventmsg
    self.session.instantiate(handler=self)
  File "/usr/lib/python2.7/dist-packages/core/session.py", line 625, in instantiate
    if self.emane.startup() == self.emane.NOT_READY:
  File "/usr/lib/python2.7/dist-packages/core/emane/emane.py", line 331, in startup
    self.buildxml()
  File "/usr/lib/python2.7/dist-packages/core/emane/emane.py", line 477, in buildxml
    self.buildnemxml()
  File "/usr/lib/python2.7/dist-packages/core/emane/emane.py", line 738, in buildnemxml
    nems = emanenode.buildnemxmlfiles(self)
  File "/usr/lib/python2.7/dist-packages/core/emane/nodes.py", line 148, in buildnemxmlfiles
    self.model.buildnemxmlfiles(emane, ifc=None)
  File "/usr/lib/python2.7/dist-packages/core/emane/rfpipe.py", line 112, in buildnemxmlfiles
    self.valueof("transmissioncontrolmap", values) is "":
  File "/usr/lib/python2.7/dist-packages/core/conf.py", line 347, in valueof
    i = cls.getnames().index(name)
ValueError: tuple.index(x): x not in tuple

**Comment by trentbottin** [comment]
The distribution version of CORE 4.8 at this time is not compatible.  The nightly snapshot appears to address the issue.
