### ISSUE TITLE
netifs difference between definition and runtime?

### ISSUE THREAD

**Issue by andreas-ibm** [coreemu/core#149]
Hi,

Trying to use and improve the ovs service and have come across a bug that seems to span more than this service.

This service needs to enumerate the interfaces on the node:
```
        for ifc in node.netifs():

```
which in old versions used to return something! now it's `None`.
Looking at the core-daemon log contains the smoking gun:
```
[E 180416 15:16:52 corehandlers:handle_message:462] Thread-3: exception while handling message: CoreLinkMessage <msgtype = LINK, flags = 0x1 <ADD>>
      TYPE: 1
      N1_NUMBER: 4
      N2_NUMBER: 3
      DELAY: 0
      BANDWIDTH: 0
      PER: 0
      DUP: 0
      JITTER: 0
      INTERFACE2_IP6: 2001:3::20
      INTERFACE1_NUMBER: 1
      INTERFACE1_MAC: 00:00:00:aa:01:21
      INTERFACE2_NUMBER: 1
      INTERFACE2_IP4: 10.0.1.21
      INTERFACE2_IP4_MASK: 24
      INTERFACE2_MAC: 00:00:00:aa:01:22
      INTERFACE2_IP6_MASK: 64
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/core_python-5.0-py2.7.egg/core/corehandlers.py", line 458, in handle_message
        replies = message_handler(message)
      File "/usr/local/lib/python2.7/dist-packages/core_python-5.0-py2.7.egg/core/corehandlers.py", line 864, in handle_link_message
        hwaddr=mac1, ifindex=interface_index1, ifname=interface_name1
      File "/usr/local/lib/python2.7/dist-packages/core_python-5.0-py2.7.egg/core/netns/vnode.py", line 455, in newnetif
        ifindex = self.newveth(ifindex=ifindex, ifname=ifname, net=net)
      File "/usr/local/lib/python2.7/dist-packages/core_python-5.0-py2.7.egg/core/netns/vnode.py", line 301, in newveth
        result, output = self.cmdresult(["ip", "link", "show", veth.name])
      File "/usr/local/lib/python2.7/dist-packages/core_python-5.0-py2.7.egg/core/netns/vnode.py", line 165, in cmdresult
        return self.vnodeclient.cmdresult(args)
    AttributeError: 'NoneType' object has no attribute 'cmdresult'
```

Looking at the code I can't for the life of me see how it used to work,  I see some bits have moved around, but at the core it seems the same in the old and new version, they both perform a:
```
                if self.session.state > EventTypes.DEFINITION_STATE.value:
                    start = True
```
but they don't seem to use that value much..

ah-hah!
This looks new:
```
            # retrieve interface information
            result, output = self.cmdresult(["ip", "link", "show", veth.name])
            logger.info("interface command output: %s", output)
            output = output.split("\n")
            veth.flow_id = int(output[0].strip().split(":")[0]) + 1
            logger.info("interface flow index: %s - %s", veth.name, veth.flow_id)
            veth.hwaddr = output[1].strip().split()[1]
            logger.info("interface mac: %s - %s", veth.name, veth.hwaddr)
```
changing it to:
```
            if self.up:
                # retrieve interface information
                result, output = self.cmdresult(["ip", "link", "show", veth.name])
                logger.info("interface command output: %s", output)
                output = output.split("\n")
                veth.flow_id = int(output[0].strip().split(":")[0]) + 1
                logger.info("interface flow index: %s - %s", veth.name, veth.flow_id)
                veth.hwaddr = output[1].strip().split()[1]
                logger.info("interface mac: %s - %s", veth.name, veth.hwaddr)
```
gives us our interfaces again!

Is it safe to do so, if it is I can fork and submit a PR

**Comment by bharnden** [comment]
This was caught and in the beta release already, as seen here:
https://github.com/coreemu/core/blob/rel/5.1/daemon/core/netns/vnode.py

Thanks for catching this and looking into it.

**Comment by andreas-ibm** [comment]
Thanks! I had a few "improvements" in mind for the OVS service, who can I discuss them with?

**Comment by bharnden** [comment]
There is an OVS mode as well, that may help you. "sudo core-daemon ovs". Otherwise I would be glad to hear them here or you can create an issue with your thoughts/suggestions.

Thanks!
