### ISSUE TITLE
core-daemon won't start without EMANE installed

### ISSUE THREAD

**Issue by siliconja** [coreemu/core#152]
Latest 5.1 beta 3, Ubuntu 16.04.

EMANE is not installed and core-daemon cannot start:

> $ sudo core-daemon 
2018-04-19 07:50:27,893 - INFO - emanemanifest:<module> - emane 1.2.1 not found
Traceback (most recent call last):
  File "/usr/local/bin/core-daemon", line 16, in <module>
    from core import corehandlers
  File "/usr/local/lib/python2.7/dist-packages/core/corehandlers.py", line 17, in <module>
    from core.coreserver import CoreServer
  File "/usr/local/lib/python2.7/dist-packages/core/coreserver.py", line 13, in <module>
    from core.session import Session
  File "/usr/local/lib/python2.7/dist-packages/core/session.py", line 28, in <module>
    from core.emane.emanemanager import EmaneManager
  File "/usr/local/lib/python2.7/dist-packages/core/emane/emanemanager.py", line 15, in <module>
    from core.emane.bypass import EmaneBypassModel
  File "/usr/local/lib/python2.7/dist-packages/core/emane/bypass.py", line 5, in <module>
    from core.emane import emanemodel
  File "/usr/local/lib/python2.7/dist-packages/core/emane/emanemodel.py", line 74, in <module>
    class EmaneModel(WirelessModel):
  File "/usr/local/lib/python2.7/dist-packages/core/emane/emanemodel.py", line 96, in EmaneModel
    phy_config = emanemanifest.parse(phy_xml, phy_defaults)
  File "/usr/local/lib/python2.7/dist-packages/core/emane/emanemanifest.py", line 81, in parse
    manifest_file = manifest.Manifest(manifest_path)
NameError: global name 'manifest' is not defined

**Comment by siliconja** [comment]
Here is a quick fix:
```
diff --git a/daemon/core/emane/emanemanifest.py b/daemon/core/emane/emanemanifest.py
index e97349c..ae1f2b1 100644
--- a/daemon/core/emane/emanemanifest.py
+++ b/daemon/core/emane/emanemanifest.py
@@ -78,8 +78,11 @@ def parse(manifest_path, defaults):
     """
 
     # load configuration file
-    manifest_file = manifest.Manifest(manifest_path)
-    manifest_configurations = manifest_file.getAllConfiguration()
+    try:
+        manifest_file = manifest.Manifest(manifest_path)
+        manifest_configurations = manifest_file.getAllConfiguration()
+    except NameError:
+        return []
 
     configurations = []
     for config_name in sorted(manifest_configurations):

```

**Comment by bharnden** [comment]
Thanks for this, pushed update to fix the emane requirement for now.
