### ISSUE TITLE
linkconfig() got an unexpected keyword argument 'netif'

### ISSUE THREAD

**Issue by andreas-ibm** [coreemu/core#171]
Started CORE in ovs mode and ran a basic emulation with 3 ovs nodes and 6 PCs attached to them. On startup I get:

```
python[18333]: Traceback (most recent call last):
python[18333]:   File "/usr/lib/python2.7/dist-packages/core/corehandlers.py", line 518, in handle_message
python[18333]:     replies = message_handler(message)
python[18333]:   File "/usr/lib/python2.7/dist-packages/core/corehandlers.py", line 746, in handle_link_message
python[18333]:     self.session.add_link(node_one_id, node_two_id, interface_one, interface_two, link_options)
python[18333]:   File "/usr/lib/python2.7/dist-packages/core/emulator/coreemu.py", line 254, in add_link
python[18333]:     link_config(net_one, interface, link_options)
python[18333]:   File "/usr/lib/python2.7/dist-packages/core/emulator/coreemu.py", line 86, in link_config
python[18333]:     network.linkconfig(**config)
python[18333]: TypeError: linkconfig() got an unexpected keyword argument 'netif'
```

and it fails to create the bridges...

The affected code is:
```
    config = {
        "netif": interface,
        "bw": link_options.bandwidth,
        "delay": link_options.delay,
        "loss": link_options.per,
        "duplicate": link_options.dup,
        "jitter": link_options.jitter,
        "netif2": interface_two
    }

    # hacky check here, because physical and emane nodes do not conform to the same linkconfig interface
    if not nodeutils.is_node(network, [NodeTypes.EMANE, NodeTypes.PHYSICAL]):
        config["devname"] = devname

    network.linkconfig(**config)
```

and if I change it to:
```
    config = {
        "netif": interface,
        "bw": link_options.bandwidth,
        "delay": link_options.delay,
        "loss": link_options.per,
        "duplicate": link_options.dup,
        "jitter": link_options.jitter,
        "netif2": interface_two
    }

    # hacky check here, because physical and emane nodes do not conform to the same linkconfig interface
    if not nodeutils.is_node(network, [NodeTypes.EMANE, NodeTypes.PHYSICAL]):
        config["devname"] = devname

    network.linkconfig(config["netif"],config["bw"],config["delay"],config["loss"],config["duplicate"],config["jitter"],config["netif2"],config["devname"])
```

then life goes better and i have a working setup. Is this a python issue? I'm running python 2.7.12 in a fairly standard Ubuntu 16.04 setup....

**Comment by andreas-ibm** [comment]
OK, well I'm switching to OVS mode on a more permanent basis, since LinuxBridge seems to have taken offence and stopped working (weirdly, only ARP messages get passed through the bridges, and nothing else).

So I'll keep you posted on any other problems I hit, I promise I'll try to fix them myself before I come moaning ;-)
