### ISSUE TITLE
OVS mode and control network

### ISSUE THREAD

**Issue by andreas-ibm** [coreemu/core#172]
Started CORE in OVS mode and am having a little trouble with the control bridge.
Here's the imn (cunningly disguised as a .txt):
[small-ovs-external-ONOS.txt](https://github.com/coreemu/core/files/2167227/small-ovs-external-ONOS.txt)
When I start it the control network is unattached, and these errors on the host if I query the vswitch:
```
     Bridge control
        Port "veth1.99.2e"
            Interface "veth1.99.2e"
                error: "could not open network device veth1.99.2e (No such device)"
        Port "veth3.99.2e"
            Interface "veth3.99.2e"
                error: "could not open network device veth3.99.2e (No such device)"
        Port "veth7.99.2e"
            Interface "veth7.99.2e"
                error: "could not open network device veth7.99.2e (No such device)"
        Port "veth6.99.2e"
            Interface "veth6.99.2e"
                error: "could not open network device veth6.99.2e (No such device)"
        Port "veth9.99.2e"
            Interface "veth9.99.2e"
                error: "could not open network device veth9.99.2e (No such device)"
        Port "veth2.99.2e"
            Interface "veth2.99.2e"
                error: "could not open network device veth2.99.2e (No such device)"
        Port "veth4.99.2e"
            Interface "veth4.99.2e"
                error: "could not open network device veth4.99.2e (No such device)"
        Port "veth8.99.2e"
            Interface "veth8.99.2e"
                error: "could not open network device veth8.99.2e (No such device)"
        Port control
            Interface control
                type: internal
        Port "veth5.99.2e"
            Interface "veth5.99.2e"
                error: "could not open network device veth5.99.2e (No such device)"
```
I can see there's a set of veth interfaces that aren't attached to ovs:
```
512: b.33918.6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
517: b.7538.6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
522: b.509.6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
527: b.56698.6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
532: b.25620.6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
538: veth1.99.6@if537: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
540: veth2.99.6@if539: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
542: veth3.99.6@if541: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
544: veth4.99.6@if543: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
546: veth5.99.6@if545: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
291: b.ctrl0net.33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
548: veth6.99.6@if547: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
550: veth7.99.6@if549: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
552: veth8.99.6@if551: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
554: veth9.99.6@if553: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
444: control: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
446: lxcbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
492: b.61247.6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
497: b.15611.6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
502: b.52884.6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
507: b.62954.6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
```
and if I add them:
```bash
$ovs-vsctl add-port control veth1.99.6
$ovs-vsctl add-port control veth2.99.6
$ovs-vsctl add-port control veth3.99.6
$ovs-vsctl add-port control veth4.99.6
$ovs-vsctl add-port control veth5.99.6
$ovs-vsctl add-port control veth6.99.6
$ovs-vsctl add-port control veth7.99.6
$ovs-vsctl add-port control veth8.99.6
$ovs-vsctl add-port control veth9.99.6
```
then the guests can talk to the host again.

I'll start digging into source, is there a particular place to look to fix this?

**Comment by andreas-ibm** [comment]
Yes, I'm using it that way.

Not entirely sure what you mean about not tested from imn, is XML the preferred storage medium? I'll have to double-check, but I think I hit the same problem if I create the scenario from scratch (i.e. don't load from imn).

**Comment by andreas-ibm** [comment]
I *think* I see what you mean about the OVS service, the reason I'm using the OVS service still even though CORE is in OVS mode, is that it lets me customise the OVS config (in this case to use my currently experimental ONOS service).

I *was* happy to use LinuxBridge for the remainder of my bridging needs, but due to LinuxBridge getting in a sulk and refusing to bridge anything apart from ARP I took the step to switch to OVS.

**Comment by andreas-ibm** [comment]
In any case, I'm sure it's a relatively easy for (somehow it's using "2e" instead of "6" somewhere), so a teensy pointer to the right files I should be looking at and I'll try to fix it myself (and submit a PR)

**Comment by andreas-ibm** [comment]
Ahh, the plot thickens.. The errors I was seeing from ovs-vsctl was from previous control networks that hadn't been cleaned up properly, when I clean them up and restart I get:
```
ovs-vsctl[27799]: ovs|00001|vsctl|INFO|Called as /usr/bin/ovs-vsctl add-br b.ctrl0net.eb
python[27617]: 2018-07-09 15:06:53,189 - ERROR - corehandlers:handle_message - Thread-2: exception while handling message: CoreEventMessage <msgtype = EVENT, flags = 0x0 <>>
python[27617]:   TYPE: 3
python[27617]: Traceback (most recent call last):
python[27617]:   File "/usr/lib/python2.7/dist-packages/core/corehandlers.py", line 518, in handle_message
python[27617]:     replies = message_handler(message)
python[27617]:   File "/usr/lib/python2.7/dist-packages/core/corehandlers.py", line 1063, in handle_event_message
python[27617]:     self.session.instantiate()
python[27617]:   File "/usr/lib/python2.7/dist-packages/core/session.py", line 739, in instantiate
python[27617]:     self.add_remove_control_interface(node=None, remove=False)
python[27617]:   File "/usr/lib/python2.7/dist-packages/core/session.py", line 1079, in add_remove_control_interface
python[27617]:     control_net = self.add_remove_control_net(net_index, remove, conf_required)
python[27617]:   File "/usr/lib/python2.7/dist-packages/core/session.py", line 1054, in add_remove_control_net
python[27617]:     updown_script=updown_script, serverintf=server_interface)
python[27617]:   File "/usr/lib/python2.7/dist-packages/core/session.py", line 525, in add_object
python[27617]:     obj = cls(self, *clsargs, **clskwds)
python[27617]:   File "/usr/lib/python2.7/dist-packages/core/netns/openvswitch.py", line 354, in __init__
python[27617]:     OvsNet.__init__(self, session, objid=objid, name=name, start=start)
python[27617]:   File "/usr/lib/python2.7/dist-packages/core/netns/openvswitch.py", line 77, in __init__
python[27617]:     self.startup()
python[27617]:   File "/usr/lib/python2.7/dist-packages/core/netns/openvswitch.py", line 366, in startup
python[27617]:     if self.hostid:
python[27617]: AttributeError: 'OvsCtrlNet' object has no attribute 'hostid'
```
So I'll poke that till it stops complaining ;-)

**Comment by andreas-ibm** [comment]
Ah-hah, that was a small init problem:

```
diff --git a/daemon/core/netns/openvswitch.py b/daemon/core/netns/openvswitch.py
index 46ba2f2..874445b 100644
--- a/daemon/core/netns/openvswitch.py
+++ b/daemon/core/netns/openvswitch.py
@@ -351,12 +351,12 @@ class OvsCtrlNet(OvsNet):

     def __init__(self, session, objid="ctrlnet", name=None, prefix=None, hostid=None,
                  start=True, assign_address=True, updown_script=None, serverintf=None):
-        OvsNet.__init__(self, session, objid=objid, name=name, start=start)
         self.prefix = ipaddress.Ipv4Prefix(prefix)
         self.hostid = hostid
         self.assign_address = assign_address
         self.updown_script = updown_script
         self.serverintf = serverintf
+        OvsNet.__init__(self, session, objid=objid, name=name, start=start)

     def startup(self):
         if self.detectoldbridge():
```

`OvsNet.__init__` was calling startup, but the member attributes hadn't been initialised yet.

**Comment by andreas-ibm** [comment]
ahh, that was the solution, if you add that patch to the repo it'll fix the problem :-)

**Comment by bharnden** [comment]
Thanks, having someone play around with it should help catch issues like these, so that is good. I will pull this into the 5.2 Beta.

As far as IMN/XML, I meant that saving state to those files with OVS mode had not been tested at all, so it may or may not cause issues.

Thanks for your feedback.
