### ISSUE TITLE
LXC containers do not open when start the execute mode

### ISSUE THREAD

**Issue by adityasriv22** [coreemu/core#175]
I am facing this issue that when I start the core-daemon every thing is fine, but when I start the execute mode, this error is thrown in the console

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/core/corehandlers.py", line 518, in handle_message
    replies = message_handler(message)
  File "/usr/local/lib/python2.7/dist-packages/core/corehandlers.py", line 1063, in handle_event_message
    self.session.instantiate()
  File "/usr/local/lib/python2.7/dist-packages/core/session.py", line 746, in instantiate
    self.broker.startup()
  File "/usr/local/lib/python2.7/dist-packages/core/broker.py", line 137, in startup
    self.addnettunnels()
  File "/usr/local/lib/python2.7/dist-packages/core/broker.py", line 434, in addnettunnels
    self.addnettunnel(n)
  File "/usr/local/lib/python2.7/dist-packages/core/broker.py", line 448, in addnettunnel
    raise KeyError("network node %s not found" % node_id)
KeyError: 'network node 2 not found'

**Comment by bharnden** [comment]
It's hard to tell what your specific issue is without knowing more about what scenario you are trying to run, the layout, etc

Ideally something that could be attempted to be replicated to understand what's going on.

Thanks for sharing though.

**Comment by andreas-ibm** [comment]
Could you share your imn config file perhaps (or make a smaller one that you *can* share?) 
Which version of core are you using>

**Comment by adityasriv22** [comment]
Thank you but I have solved ,it was because my LXC daemon did not have sudo privledges
