### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 224: ordinal not in range(128)

### ISSUE THREAD

**Issue by hugo921** [coreemu/core#217]
who can tell me why ?when i start to run core ,core-daemon log like below.
2018-11-29 00:05:58,071 - INFO - vnode:mount - node(n1) mounting: /tmp/pycore.46300/n1.conf/var.lock.subsys at /var/lock/subsys/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 224: ordinal not in range(128)
Logged from file service.py, line 474

**Comment by bharnden** [comment]
What OS?
What version of CORE?
What services? Any custom services?
