### ISSUE TITLE
"core" package not importable

### ISSUE THREAD

**Issue by emirljuca** [coreemu/core#230]
I downloaded the python package for CORE using the following command
```
sudo dpkg -i python-core_systemd_5.2_all.deb
``` 
However, I still don't seem to get the python package installed correctly. When opening python2.7 I get that there is no module named core. I am using Ubuntu 18.04.

**Comment by bharnden** [comment]
I would build latest from master, since that has some fixes that are not in a formal package. Beyond that you can do the following to see why you are having issues.

If you run the following on the deb file you referenced.

```shell
dpkg -c python-core_systemd_5.2_all.deb
```

You will see all the files listed, including the python path installed to, which is **/usr/lib/python2.7/dist-packages**.

You can see what is being picked up on your python path with the following, after opening a python shell.

```python
import sys
for i in sys.path: print(i)
```

If you are not seeing the path referenced above, that would explain why you cannot import it.

This also assume the default version of python you are attempting to import in is python 2 and not python 3.

**Comment by emirljuca** [comment]
Ahh I see, okay. My python2.7 points to a different directory then what core installs to
```
CORE
./usr/lib/python2.7/dist-packages/
```
```
PYTHON
/usr/local/lib/python2.7/site-packages
```
How can I adjust the python path to point correctly to where CORE python files are?

**Comment by bharnden** [comment]
Did you build python from source? If so you could potentially rebuild and install with the prefix set to /usr instead of /usr/local.

Otherwise one way would be to leverage the environment variable PYTHONPATH and set that accordingly within the service file or within the sudo environment when running something using core directly.

**Comment by emirljuca** [comment]
Ahh okay thank you! I have, I believe, been able to get the right environment
```
/home/user/base/python2_CORE
/usr/lib/python2.7/dist-packages
/usr/local/lib/python27.zip
/usr/local/lib/python2.7
/usr/local/lib/python2.7/plat-linux2
/usr/local/lib/python2.7/lib-tk
/usr/local/lib/python2.7/lib-old
/usr/local/lib/python2.7/lib-dynload
/home/user/.local/lib/python2.7/site-packages
/home/user/.local/lib/python2.7/site-packages
/usr/local/lib/python2.7/site-packages
```
However I am getting the following error
```
2019-02-25 18:10:44,940 - WARNING - nodes:<module> - compatible emane python bindings not installed
2019-02-25 18:10:44,949 - WARNING - emanemanifest:<module> - compatible emane python bindings not installed
Traceback (most recent call last):
  File "xml_parser_python2.py", line 7, in <module>
    from core.emulator.coreemu import CoreEmu
  File "/usr/lib/python2.7/dist-packages/core/emulator/coreemu.py", line 19, in <module>
    from core.session import Session
  File "/usr/lib/python2.7/dist-packages/core/session.py", line 26, in <module>
    from core.emane.emanemanager import EmaneManager
  File "/usr/lib/python2.7/dist-packages/core/emane/emanemanager.py", line 18, in <module>
    from core.emane.bypass import EmaneBypassModel
  File "/usr/lib/python2.7/dist-packages/core/emane/bypass.py", line 6, in <module>
    from core.emane import emanemodel
  File "/usr/lib/python2.7/dist-packages/core/emane/emanemodel.py", line 12, in <module>
    from core.xml import emanexml
  File "/usr/lib/python2.7/dist-packages/core/xml/emanexml.py", line 3, in <module>
    from lxml import etree
ImportError: cannot import name etree
```
From the following import train
```
SERVICES = "/home/user/.core/myservices"
from core.emulator.coreemu import CoreEmu
from core.netns.nodes import PtpNet, WlanNode
from core.emane.nodes import EmaneNode
from core.service import ServiceManager
from core.enumerations import EventTypes
from core.data import LinkData
import numpy
from itertools import combinations
from pandas import DataFrame
```

**Comment by bharnden** [comment]
Your missing python library lxml

**Comment by emirljuca** [comment]
It seems to already be downloaded, have you guys used a different version? This is what I am getting...
```
user@ubuntu:~user/base/python2_CORE$ pip2 install --user lxml
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: lxml in /usr/lib/python2.7/dist-packages (4.2.1)
user@ubuntu:~/user/base/python2_CORE$ sudo python2
[sudo] password for user: 
Python 2.7.15 (default, Feb 14 2019, 13:22:37) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxml
>>> 
```

**Comment by bharnden** [comment]
Can you run the specific import statement that it is failing on from the python shell like above?

```python
from lxml import etree
```
Otherwise this file lists specific version used:
https://github.com/coreemu/core/blob/master/daemon/requirements.txt

**Comment by emirljuca** [comment]
I was getting the error I showed before with etree...
```
>>> from lxml import etree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name etree
```
I am not really able to download the right version with pip since pip fails with a gcc error under the old version.
```
    compilation terminated.
    Compile failed: command 'gcc' failed with exit status 1
    cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitTdjvQJ.c -o tmp/xmlXPathInitTdjvQJ.o
    /tmp/xmlXPathInitTdjvQJ.c:2:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^~~~
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-MHIu9Y/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-qpDPwi/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-MHIu9Y/lxml/
```

Do you know of another way to download the older version?

**Comment by bharnden** [comment]
I have a box with Ubuntu 18.04 that I can run things fine in.

It is using lxml from the system package manager as opposed to pip. Maybe try clearing out whatever you have installed and try installing that. It is version 4.2.1-1 for completeness.

```shell
pip uninstall lxml

sudo apt install python-lxml
```

**Comment by emirljuca** [comment]
I seem to get the error for etree only when I install from python-lxml. When I use pip to download the lxml package , I don't get the same error...
```
AFTER PIP INSTALL LXML
Python 2.7.15 (default, Feb 14 2019, 13:22:37) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named core
>>> from lxml import etree
>>> exit()
```
```
AFTER INSTALL PYTHON-LXML
Python 2.7.15 (default, Feb 14 2019, 13:22:37) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from lxml import etree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name etree
```

**Comment by bharnden** [comment]
In one case you can't import core, but can import etree. The other you cant import etree, but maybe core?

You should be able to do both, there must be something going on with the python environment and paths it is looking within.

Initially I saw /usr/local for your python installation. So did you install python2 from source? was there not already python2 on the machine? It's possible you have 2 versions of python2 on the machine and both are included within their search path, or one is a subset of the other.

I never had to install python2 from source, but I was just using the Ubuntu Desktop distributed. If you are coming from some type of minimal install, that may be different then.

**Comment by emirljuca** [comment]
The two situations described in my comment above were from the same python interpreter but with different lxml configurations. Both of python interpreter instances have a path that points to where core exists.

I did download python from source which may be the problem but I thought that python2 was not included with the new version of Ubuntu. I can try doing everything from a fresh iso of Ubuntu 18.04?

Maybe I can follow the tutorial again? I am worried about quagga though since I need the wireless to work. It's been my experience that I need quagga-mr to work for wireless connections to work, and downloading quagga-mr has been a challenge under the new Ubuntu version.

**Comment by bharnden** [comment]
It's probably easiest to use 16.04 if possible. I recall there being some pain points with others trying to use the mdr quagga with 18.

You should have been able to import core then in your above example and that was failing, so something is off there.

**Comment by emirljuca** [comment]
For our team, we need to use the newest version of Ubuntu. I have gotten the core package for python 2 in working order now by following these steps from a fresh Ubuntu...

1. Update and upgrade Ubuntu
```
sudo apt-get update
sudo apt-get upgrade -y
```
2.  Update with all the necessary software packages for CORE, Quagga, and EMANE
```
sudo apt-get install git curl python python-pip libnss3-tools build-essential gawk libreadline-dev pkg-config libc-ares-dev gcc g++ autoconf automake libtool libxml2-dev libprotobuf-dev python-protobuf libpcap-dev libpcre3-dev uuid-dev debhelper pkg-config python-setuptools protobuf-compiler git dh-python python3-protobuf python3-setuptools libev-dev bridge-utils ebtables python-dev python-sphinx python-lxml python-enum34 tk libtk-img python3-lxml python3-emane -y 
```
3. Get EMANE source, CORE source, and Quagga tar files
```
cd ~/Downloads
git clone https://github.com/adjacentlink/emane.git
git clone https://github.com/coreemu/core.git
wget https://downloads.pf.itd.nrl.navy.mil/ospf-manet/quagga-0.99.21mr2.2/quagga-0.99.21mr2.2.tar.gz
```
4. Build the debs for EMANE, run the configuration for CORE, and unzip and configure for Quagga
```
cd emane
./autogen.sh && ./configure && make deb
cd ../
cd core
./bootstrap.sh
./configure
make
sudo make install
cd ../
tar xzf quagga-0.99.21mr2.2.tar.gz
cd quagga-0.99
./configure --enable-user=root --enable-group=root --with-cflags=-ggdb --sysconfdir=/usr/local/etc/quagga --enable-vtysh --localstatedir=/var/run/quagga
make
sudo make install
```
5. Start the CORE daemon and GUI

However I still have a problem with quagga where zebra doesn't open up right while in CORE and also I get an error building the docs for CORE. Not sure if these are bad problems but I am not sure how to fix them. I am now able to get the "core" package and "lxml" package working in my python interpreter.

**Comment by bharnden** [comment]
Quagga/zebra isn't something I am familiar with, I do know that quagga package you built is really old and there has been talk about what would be the right thing to refer to for a default.

As far as the docs, that shouldn't be important, since it's mainly intended to be hosted on GitHub. I would be interested to see your issue though. I assume a python dependency issue.

**Comment by emirljuca** [comment]
I can post those errors in a separate issue if you'd like? I will post them here for now and move them over if you think that is right.

Here are the issues that I see with Quagga-MR when running a MR router node connected to another MR router node with a WLAN connection...
The topology is...
![image](https://user-images.githubusercontent.com/43454326/53743285-714e7980-3e68-11e9-8ef0-86db4cccdcc7.png)
```
2019-03-04 07:24:31,148 - INFO - corehandlers:handle - client disconnected
2019-03-04 07:24:31,151 - INFO - broker:addserver - adding broker server(localhost): None:None
2019-03-04 07:24:31,666 - INFO - emanemanager:emane_check - using EMANE: 1.2.3
2019-03-04 07:24:31,667 - INFO - emanemanager:load_models - loading emane model: EmaneRfPipeModel
2019-03-04 07:24:31,667 - INFO - emanemanager:load_models - loading emane model: EmaneIeee80211abgModel
2019-03-04 07:24:31,667 - INFO - emanemanager:load_models - loading emane model: EmaneCommEffectModel
2019-03-04 07:24:31,667 - INFO - emanemanager:load_models - loading emane model: EmaneBypassModel
2019-03-04 07:24:31,667 - INFO - emanemanager:load_models - loading emane model: EmaneTdmaModel
2019-03-04 07:24:31,667 - INFO - coreemu:create_session - created session: 36345
2019-03-04 07:24:31,667 - INFO - session:set_state - changing session(36345) to state DEFINITION_STATE
2019-03-04 07:24:31,677 - INFO - corehandlers:register - GUI has connected to session 36345 at Mon Mar  4 07:24:31 2019
2019-03-04 07:24:32,151 - INFO - corehandlers:finish - client disconnected: notifying threads
2019-03-04 07:24:32,151 - INFO - corehandlers:finish - waiting for thread: Thread-4
2019-03-04 07:24:32,186 - INFO - corehandlers:finish - connection closed: ('127.0.0.1', 33763)
2019-03-04 07:24:32,186 - INFO - coreemu:is_active - session(33763) checking if active: False
2019-03-04 07:24:32,186 - INFO - corehandlers:finish - no session clients left and not active, initiating shutdown
2019-03-04 07:24:32,186 - INFO - coreemu:delete_session - deleting session: 33763
2019-03-04 07:24:32,186 - INFO - coreemu:delete_session - shutting session down: 33763
2019-03-04 07:24:32,186 - INFO - coreemu:shutdown - session(33763) shutting down
2019-03-04 07:24:32,186 - INFO - session:set_state - changing session(33763) to state DATACOLLECT_STATE
2019-03-04 07:24:32,186 - INFO - session:set_state - changing session(33763) to state SHUTDOWN_STATE
2019-03-04 07:24:32,279 - INFO - broker:reset - clearing state
2019-03-04 07:24:32,280 - INFO - sdt:shutdown - SDT shutdown!
2019-03-04 07:24:53,323 - INFO - corehandlers:handle_session_message - request to modify to session: 36345
2019-03-04 07:24:53,442 - INFO - session:set_state - session(36345) is already in state: DEFINITION_STATE, skipping change
2019-03-04 07:24:53,443 - INFO - broker:reset - clearing state
2019-03-04 07:24:53,443 - INFO - session:set_state - changing session(36345) to state CONFIGURATION_STATE
2019-03-04 07:24:53,443 - WARNING - corehandlers:handle_event_message - unhandled event message: event type EventTypes.CONFIGURATION_STATE
2019-03-04 07:24:53,444 - INFO - corehandlers:handle_config_location - location configured: (0.0, 0.0, 0.0) = (47.5791667, -122.132322, 2.0) scale=150.0
2019-03-04 07:24:53,444 - INFO - corehandlers:handle_config_location - location configured: UTM((10, 'T'), 565249.2879168927, 5269892.809170721, 2.0)
2019-03-04 07:24:53,478 - INFO - coreemu:add_node - creating node(CoreNode) id(1) name(n1) start(True)
2019-03-04 07:24:54,058 - INFO - vnode:mount - node(n1) mounting: /tmp/pycore.36345/n1.conf/var.run at /var/run
2019-03-04 07:24:54,062 - INFO - vnode:mount - node(n1) mounting: /tmp/pycore.36345/n1.conf/var.log at /var/log
2019-03-04 07:24:54,067 - INFO - service:add_services - using default services for node(n1) type(mdr)
2019-03-04 07:24:54,067 - INFO - service:add_services - setting services for node(n1): ['zebra', 'OSPFv3MDR', 'IPForward']
2019-03-04 07:24:54,067 - INFO - service:add_services - adding service to node(n1): zebra
2019-03-04 07:24:54,067 - INFO - service:add_services - adding service to node(n1): OSPFv3MDR
2019-03-04 07:24:54,067 - INFO - service:add_services - adding service to node(n1): IPForward
2019-03-04 07:24:54,068 - INFO - coreemu:add_node - creating node(CoreNode) id(2) name(n2) start(True)
2019-03-04 07:24:54,076 - INFO - vnode:mount - node(n2) mounting: /tmp/pycore.36345/n2.conf/var.run at /var/run
2019-03-04 07:24:54,080 - INFO - vnode:mount - node(n2) mounting: /tmp/pycore.36345/n2.conf/var.log at /var/log
2019-03-04 07:24:54,084 - INFO - service:add_services - using default services for node(n2) type(mdr)
2019-03-04 07:24:54,084 - INFO - service:add_services - setting services for node(n2): ['zebra', 'OSPFv3MDR', 'IPForward']
2019-03-04 07:24:54,084 - INFO - service:add_services - adding service to node(n2): zebra
2019-03-04 07:24:54,084 - INFO - service:add_services - adding service to node(n2): OSPFv3MDR
2019-03-04 07:24:54,084 - INFO - service:add_services - adding service to node(n2): IPForward
2019-03-04 07:24:54,084 - INFO - coreemu:add_node - creating node(WlanNode) id(3) name(wlan3) start(True)
2019-03-04 07:24:56,177 - INFO - coreemu:add_link - adding link from network to node: n1 - wlan3
2019-03-04 07:24:56,311 - INFO - coreemu:add_link - adding link from network to node: n2 - wlan3
2019-03-04 07:24:56,380 - INFO - session:set_state - changing session(36345) to state INSTANTIATION_STATE
2019-03-04 07:24:56,381 - INFO - mobility:startup - checking mobility startup for node: 3
2019-03-04 07:24:56,381 - INFO - mobility:startup - node mobility configurations: OrderedDict([('basic_range', OrderedDict([('range', '275'), ('bandwidth', '54000000'), ('jitter', '0'), ('delay', '20000'), ('error', '0')]))])
2019-03-04 07:24:56,381 - INFO - conf:set_model - setting mobility model(basic_range) for node(3): OrderedDict([('range', '275'), ('bandwidth', '54000000'), ('jitter', '0'), ('delay', '20000'), ('error', '0')])
2019-03-04 07:24:56,381 - INFO - nodes:setmodel - adding model: basic_range
2019-03-04 07:24:56,381 - INFO - mobility:values_from_config - basic range model configured for WLAN 3 using range 275
2019-03-04 07:24:57,199 - INFO - session:boot_nodes - booting node: n1
2019-03-04 07:24:57,199 - INFO - session:boot_nodes - booting node: n2
2019-03-04 07:24:57,204 - INFO - service:_start_boot_paths - booting node services: zebra -> OSPFv3MDR
2019-03-04 07:24:57,205 - INFO - service:boot_service - starting node(n1) service(zebra) validation(NON_BLOCKING)
2019-03-04 07:24:57,205 - INFO - service:_start_boot_paths - booting node services: IPForward
2019-03-04 07:24:57,205 - INFO - service:boot_service - starting node(n1) service(IPForward) validation(NON_BLOCKING)
2019-03-04 07:24:57,205 - INFO - vnode:mount - node(n1) mounting: /tmp/pycore.36345/n1.conf/usr.local.etc.quagga at /usr/local/etc/quagga
2019-03-04 07:24:57,206 - INFO - service:create_service_files - node(n1) service(IPForward) creating config files
2019-03-04 07:24:57,206 - INFO - service:_start_boot_paths - booting node services: zebra -> OSPFv3MDR
2019-03-04 07:24:57,206 - INFO - service:boot_service - starting node(n2) service(zebra) validation(NON_BLOCKING)
2019-03-04 07:24:57,207 - INFO - vnode:nodefile - node(n1) added file: /tmp/pycore.36345/n1.conf/ipforward.sh; mode: 0644
2019-03-04 07:24:57,207 - INFO - vnode:mount - node(n2) mounting: /tmp/pycore.36345/n2.conf/usr.local.etc.quagga at /usr/local/etc/quagga
2019-03-04 07:24:57,207 - INFO - service:_start_boot_paths - booting node services: IPForward
2019-03-04 07:24:57,207 - INFO - service:boot_service - starting node(n2) service(IPForward) validation(NON_BLOCKING)
2019-03-04 07:24:57,208 - INFO - service:create_service_files - node(n2) service(IPForward) creating config files
2019-03-04 07:24:57,209 - INFO - vnode:nodefile - node(n2) added file: /tmp/pycore.36345/n2.conf/ipforward.sh; mode: 0644
2019-03-04 07:24:57,209 - INFO - service:validate_service - validating node(n2) service(IPForward)
2019-03-04 07:24:57,208 - INFO - service:validate_service - validating node(n1) service(IPForward)
2019-03-04 07:24:57,210 - INFO - vnode:mount - node(n1) mounting: /tmp/pycore.36345/n1.conf/var.run.quagga at /var/run/quagga
2019-03-04 07:24:57,211 - INFO - vnode:mount - node(n2) mounting: /tmp/pycore.36345/n2.conf/var.run.quagga at /var/run/quagga
2019-03-04 07:24:57,213 - INFO - service:create_service_files - node(n1) service(zebra) creating config files
2019-03-04 07:24:57,214 - INFO - vnode:nodefile - node(n1) added file: /tmp/pycore.36345/n1.conf/usr.local.etc.quagga/Quagga.conf; mode: 0644
2019-03-04 07:24:57,214 - INFO - vnode:nodefile - node(n1) added file: /tmp/pycore.36345/n1.conf/quaggaboot.sh; mode: 0644
2019-03-04 07:24:57,214 - INFO - vnode:nodefile - node(n1) added file: /tmp/pycore.36345/n1.conf/usr.local.etc.quagga/vtysh.conf; mode: 0644
2019-03-04 07:24:57,214 - INFO - service:validate_service - validating node(n1) service(zebra)
2019-03-04 07:24:57,215 - INFO - service:create_service_files - node(n2) service(zebra) creating config files
2019-03-04 07:24:57,215 - INFO - vnode:nodefile - node(n2) added file: /tmp/pycore.36345/n2.conf/usr.local.etc.quagga/Quagga.conf; mode: 0644
2019-03-04 07:24:57,215 - INFO - vnode:nodefile - node(n2) added file: /tmp/pycore.36345/n2.conf/quaggaboot.sh; mode: 0644
2019-03-04 07:24:57,215 - INFO - vnode:nodefile - node(n2) added file: /tmp/pycore.36345/n2.conf/usr.local.etc.quagga/vtysh.conf; mode: 0644
2019-03-04 07:24:57,215 - INFO - service:validate_service - validating node(n2) service(zebra)
2019-03-04 07:24:57,216 - ERROR - service:validate_service - node(n1) service(zebra) validate failed
2019-03-04 07:24:57,217 - ERROR - service:validate_service - cmd(pidof zebra): 
2019-03-04 07:24:57,218 - ERROR - service:validate_service - node(n2) service(zebra) validate failed
2019-03-04 07:24:57,218 - ERROR - service:validate_service - cmd(pidof zebra): 
2019-03-04 07:24:57,718 - INFO - service:validate_service - validating node(n1) service(zebra)
2019-03-04 07:24:57,719 - INFO - service:validate_service - validating node(n2) service(zebra)
2019-03-04 07:24:57,720 - ERROR - service:validate_service - node(n1) service(zebra) validate failed
2019-03-04 07:24:57,720 - ERROR - service:validate_service - cmd(pidof zebra): 
2019-03-04 07:24:57,721 - ERROR - service:validate_service - node(n2) service(zebra) validate failed
2019-03-04 07:24:57,721 - ERROR - service:validate_service - cmd(pidof zebra): 
2019-03-04 07:24:58,222 - INFO - service:validate_service - validating node(n1) service(zebra)
2019-03-04 07:24:58,222 - INFO - service:validate_service - validating node(n2) service(zebra)
2019-03-04 07:24:58,224 - INFO - service:boot_service - starting node(n2) service(OSPFv3MDR) validation(NON_BLOCKING)
2019-03-04 07:24:58,224 - INFO - service:boot_service - starting node(n1) service(OSPFv3MDR) validation(NON_BLOCKING)
2019-03-04 07:24:58,224 - INFO - service:create_service_files - node(n1) service(OSPFv3MDR) creating config files
2019-03-04 07:24:58,224 - INFO - service:validate_service - validating node(n1) service(OSPFv3MDR)
2019-03-04 07:24:58,224 - INFO - service:create_service_files - node(n2) service(OSPFv3MDR) creating config files
2019-03-04 07:24:58,225 - INFO - service:validate_service - validating node(n2) service(OSPFv3MDR)
2019-03-04 07:24:58,226 - ERROR - service:validate_service - node(n1) service(OSPFv3MDR) validate failed
2019-03-04 07:24:58,226 - ERROR - service:validate_service - cmd(pidof ospf6d): 
2019-03-04 07:24:58,226 - ERROR - service:validate_service - node(n2) service(OSPFv3MDR) validate failed
2019-03-04 07:24:58,226 - ERROR - service:validate_service - cmd(pidof ospf6d): 
```

Here are the issues with building the documentation
```
user@ubuntu:~/Downloads/core$ make doc
rm -rf daemon/doc/_build
rm -rf daemon/doc/core-python-5.2
rm -f core-python-5.2.tgz
make -C daemon/doc html
make[1]: Entering directory '/home/user/Downloads/core/daemon/doc'
sphinx-build -b html -d _build/doctrees  -q . _build/html

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/usr/lib/python2.7/dist-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 15, in <module>
    import sphinx_rtd_theme
ImportError: No module named sphinx_rtd_theme

Makefile:496: recipe for target 'html' failed
make[1]: *** [html] Error 1
make[1]: Leaving directory '/home/user/Downloads/core/daemon/doc'
Makefile:967: recipe for target 'doc' failed
make: *** [doc] Error 2
```

**Comment by bharnden** [comment]
You don't need to build documentation, unless you wanted pretty python documentation for writing scripts. But, if you did, you are missing the "sphinx_rt_theme" python module as indicated by the error.

The normal documentation is hosted on github: http://coreemu.github.io/core/

As far as the errors you are seeing on startup, they are potentially not an issue at all. Assuming you still see the nodes turn green and the red borders go away, you are fine. You should be able to double click and node and run "ps" to see that expected processes exist.

You are seeing validation attempts for a given service that was updated from a singular check. The logic for logging it as an error should be updated to not cause confusion.

**Comment by emirljuca** [comment]
Ahh I see okay, after downloading the  sphinx_rtd_theme with...
```
sudo -H pip install sphinx_rtd_theme
``` 
I was able to build the docs, but like you said, not necessary.

For the nodes, a green box does show briefly after startup and when I run ps I get the following...
```
root@n5:/tmp/pycore.37187/n5.conf# ps
   PID TTY          TIME CMD
    65 pts/4    00:00:00 bash
    75 pts/4    00:00:00 ps
root@n5:/tmp/pycore.37187/n5.conf# 
```
For the following topology...
![image](https://user-images.githubusercontent.com/43454326/54234433-802ad100-44e5-11e9-932b-6947f568458b.png)

**Comment by bharnden** [comment]
Looks good to me, if you are worried you are not seeing what you think you should, like zebra and ospf.

You need to run ps differently:
```bash
ps -e
```
