### ISSUE TITLE
[BUG] XML parse for bidirectional links

### ISSUE THREAD

**Issue by emirljuca** [coreemu/core#245]
**Describe the bug**
When trying to save and load an xml file with bidirectional links with different link property values, the core-daemon crashes.

**Expected behavior**
It should just work and save and load the xml without crashing

**Screenshots**
```
2019-05-07 12:04:35,353 - ERROR - corehandlers:handle_message - Thread-351: exception while handling message: CoreEventMessage <msgtype = EVENT, flags = 0x0 <>>
  TYPE: 11
  NAME: /home/user/user-repo/user/test/nrlcore/topologies/two-pc/two-pc.xml
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/core/corehandlers.py", line 492, in handle_message
    replies = message_handler(message)
  File "/usr/local/lib/python2.7/dist-packages/core/corehandlers.py", line 1475, in handle_event_message
    self.session.open_xml(filename, start=False)
  File "/usr/local/lib/python2.7/dist-packages/core/emulator/coreemu.py", line 665, in open_xml
    CoreXmlReader(self).read(file_name)
  File "/usr/local/lib/python2.7/dist-packages/core/xml/corexml.py", line 517, in read
    self.read_links()
  File "/usr/local/lib/python2.7/dist-packages/core/xml/corexml.py", line 777, in read_links
    self.session.add_link(node_one, node_two, interface_one, interface_two, link_options)
  File "/usr/local/lib/python2.7/dist-packages/core/emulator/coreemu.py", line 253, in add_link
    interface = create_interface(node_one, net_one, interface_one)
  File "/usr/local/lib/python2.7/dist-packages/core/emulator/coreemu.py", line 56, in create_interface
    ifname=interface_data.name
  File "/usr/local/lib/python2.7/dist-packages/core/netns/vnode.py", line 431, in newnetif
    ifindex = self.newveth(ifindex=ifindex, ifname=ifname, net=net)
  File "/usr/local/lib/python2.7/dist-packages/core/netns/vnode.py", line 282, in newveth
    raise e
ValueError: ifindex 0 already exists
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version 5.2.1 (20190418)
 - EMANE Version 1.2.3

**Comment by bharnden** [comment]
Thanks, will look into this when I get a chance.

**Comment by bharnden** [comment]
Hopefully is fixed on develop now
