### ISSUE TITLE
[BUG] Links and nodes disappear and change when saving an XML with loss

### ISSUE THREAD

**Issue by emirljuca** [coreemu/core#266]
**Describe the bug**
When saving an XML topology with custom nodes connected together and a loss value is added to a link parameter, when that topology loads, the nodes are converted to routers and the links are removed

**To Reproduce**
1. Have a custom node created
-  Go to CORE Node Types GUI
-  Create a new node type with some extra services (we had custom services)
2. Create a topology with just the custom nodes (we had three connected in a line)
3. Save this topology as an xml
4. Restart CORE GUI to make sure that it will still open with the custom nodes
5. Adjust one of the links to have an error rate
6. Save this XML
7. Restart CORE GUI and open this topology
 ERROR; nodes replaced by routers and links gone

**Screenshots**
BEFORE: Restarting CORE but saved XML
![image](https://user-images.githubusercontent.com/43454326/60518589-c92ead00-9caf-11e9-89b1-e3501a056277.png)

AFTER: Opening saved XML
![image](https://user-images.githubusercontent.com/43454326/60518613-d9df2300-9caf-11e9-907b-f1241897adcb.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version 5.3

**Additional context**
Some weird behavior was happening just when saving typologies with loss in an XML format **WITHOUT** having custom nodes, it was happening with custom nodes for me though

**Comment by bharnden** [comment]
Switching to IMN in the near term may be a work around, as that is saved by the GUI itself. I can look to check on this scenario soon.

Thanks.

**Comment by bharnden** [comment]
I wonder if there is something else going, do you have any errors in the log file?

I did a quick run on develop, but don't recall it having any changes that would be related. Creating something similar with a quick custom node didn't produce the same behavior.

Potentially vetting against running core-daemon yourself to help in isolating to your specific run.

```shell
sudo core-daemon
```

**Comment by emirljuca** [comment]
Hey so this is the log from me repeating the same process as described in my original posts.

```
2019-07-03 10:38:41,063 - INFO - corexml:write_nodes - writer adding node(n1)
2019-07-03 10:38:41,063 - INFO - corexml:write_nodes - writer adding node(n2)
2019-07-03 10:38:41,063 - INFO - corexml:write_nodes - writer adding node(n3)
2019-07-03 10:38:41,063 - INFO - corexml:write_nodes - writer adding node(19171)
2019-07-03 10:38:41,063 - INFO - corexml:write_nodes - writer adding node(24694)
2019-07-03 10:38:41,063 - INFO - corexml:write_nodes - writer adding node(61754)
2019-07-03 10:39:18,116 - INFO - corehandlers:handle - client disconnected
2019-07-03 10:39:18,116 - INFO - corehandlers:finish - client disconnected: notifying threads
2019-07-03 10:39:18,117 - INFO - corehandlers:finish - waiting for thread: Thread-7
2019-07-03 10:39:19,092 - INFO - corehandlers:finish - connection closed: ('127.0.0.1', 42109)
2019-07-03 10:39:19,092 - INFO - coreemu:is_active - session(42109) checking if active: False
2019-07-03 10:39:19,092 - INFO - corehandlers:finish - no session clients left and not active, initiating shutdown
2019-07-03 10:39:19,092 - INFO - coreemu:delete_session - deleting session: 42109
2019-07-03 10:39:19,092 - INFO - coreemu:delete_session - shutting session down: 42109
2019-07-03 10:39:19,092 - INFO - coreemu:shutdown - session(42109) shutting down
2019-07-03 10:39:19,092 - INFO - session:set_state - changing session(42109) to state DATACOLLECT_STATE
2019-07-03 10:39:19,092 - INFO - session:set_state - changing session(42109) to state SHUTDOWN_STATE
2019-07-03 10:39:19,093 - INFO - broker:reset - clearing state
2019-07-03 10:39:19,093 - INFO - sdt:shutdown - SDT shutdown!
2019-07-03 10:39:20,230 - INFO - broker:addserver - adding broker server(localhost): None:None
2019-07-03 10:39:20,736 - INFO - emanemanager:emane_check - using EMANE: 1.2.3
2019-07-03 10:39:20,736 - INFO - emanemanager:load_models - loading emane model: EmaneRfPipeModel
2019-07-03 10:39:20,736 - INFO - emanemanager:load_models - loading emane model: EmaneIeee80211abgModel
2019-07-03 10:39:20,736 - INFO - emanemanager:load_models - loading emane model: EmaneCommEffectModel
2019-07-03 10:39:20,736 - INFO - emanemanager:load_models - loading emane model: EmaneBypassModel
2019-07-03 10:39:20,736 - INFO - emanemanager:load_models - loading emane model: EmaneTdmaModel
2019-07-03 10:39:20,736 - INFO - coreemu:create_session - created session: 37043
2019-07-03 10:39:20,736 - INFO - session:set_state - changing session(37043) to state DEFINITION_STATE
2019-07-03 10:39:20,748 - INFO - corehandlers:register - GUI has connected to session 37043 at Wed Jul  3 10:39:20 2019
2019-07-03 10:39:22,690 - INFO - corehandlers:handle - client disconnected
2019-07-03 10:39:22,690 - INFO - corehandlers:finish - client disconnected: notifying threads
2019-07-03 10:39:22,691 - INFO - corehandlers:finish - waiting for thread: Thread-10
2019-07-03 10:39:22,692 - INFO - broker:addserver - adding broker server(localhost): None:None
2019-07-03 10:39:22,757 - INFO - corehandlers:finish - connection closed: ('127.0.0.1', 37043)
2019-07-03 10:39:22,758 - INFO - coreemu:is_active - session(37043) checking if active: False
2019-07-03 10:39:22,758 - INFO - corehandlers:finish - no session clients left and not active, initiating shutdown
2019-07-03 10:39:22,758 - INFO - coreemu:delete_session - deleting session: 37043
2019-07-03 10:39:22,758 - INFO - coreemu:delete_session - shutting session down: 37043
2019-07-03 10:39:22,758 - INFO - coreemu:shutdown - session(37043) shutting down
2019-07-03 10:39:22,758 - INFO - session:set_state - changing session(37043) to state DATACOLLECT_STATE
2019-07-03 10:39:22,758 - INFO - session:set_state - changing session(37043) to state SHUTDOWN_STATE
2019-07-03 10:39:22,758 - INFO - broker:reset - clearing state
2019-07-03 10:39:22,758 - INFO - sdt:shutdown - SDT shutdown!
2019-07-03 10:39:23,199 - INFO - emanemanager:emane_check - using EMANE: 1.2.3
2019-07-03 10:39:23,199 - INFO - emanemanager:load_models - loading emane model: EmaneRfPipeModel
2019-07-03 10:39:23,199 - INFO - emanemanager:load_models - loading emane model: EmaneIeee80211abgModel
2019-07-03 10:39:23,199 - INFO - emanemanager:load_models - loading emane model: EmaneCommEffectModel
2019-07-03 10:39:23,199 - INFO - emanemanager:load_models - loading emane model: EmaneBypassModel
2019-07-03 10:39:23,199 - INFO - emanemanager:load_models - loading emane model: EmaneTdmaModel
2019-07-03 10:39:23,199 - INFO - coreemu:create_session - created session: 39409
2019-07-03 10:39:23,200 - INFO - session:set_state - changing session(39409) to state DEFINITION_STATE
2019-07-03 10:39:23,212 - INFO - corehandlers:register - GUI has connected to session 39409 at Wed Jul  3 10:39:23 2019
2019-07-03 10:39:23,213 - INFO - broker:reset - clearing state
2019-07-03 10:39:23,213 - INFO - corexml:read_default_services - reading default services for nodes(mdr): ['zebra', 'OSPFv3MDR', 'IPForward']
2019-07-03 10:39:23,213 - INFO - corexml:read_default_services - reading default services for nodes(PC): ['DefaultRoute']
2019-07-03 10:39:23,213 - INFO - corexml:read_default_services - reading default services for nodes(host): ['DefaultRoute', 'SSH']
2019-07-03 10:39:23,213 - INFO - corexml:read_default_services - reading default services for nodes(prouter): ['zebra', 'OSPFv2', 'OSPFv3', 'IPForward']
2019-07-03 10:39:23,213 - INFO - corexml:read_default_services - reading default services for nodes(router): ['zebra', 'OSPFv2', 'OSPFv3', 'IPForward']
2019-07-03 10:39:23,213 - INFO - corexml:read_session_metadata - reading session metadata: {'global_options': 'interface_names=no ip_addresses=yes ipv6_addresses=yes node_labels=yes link_labels=yes show_api=no background_images=no annotations=yes grid=yes traffic_start=0', 'canvas c1': '{name {Canvas1}}'}
2019-07-03 10:39:23,213 - INFO - corexml:read_session_origin - reading session reference geo: 47.5791667, -122.132322, 2.0
2019-07-03 10:39:23,213 - INFO - corexml:read_session_origin - reading session reference scale: 150.0
2019-07-03 10:39:23,213 - INFO - corexml:read_device - reading node id(1) model(router) name(n1)
2019-07-03 10:39:23,214 - INFO - coreemu:add_node - creating node(CoreNode) id(1) name(n1) start(False)
2019-07-03 10:39:23,214 - INFO - service:add_services - setting services for node(n1): ['zebra', 'OSPFv2', 'OSPFv3', 'IPForward']
2019-07-03 10:39:23,214 - INFO - service:add_services - adding service to node(n1): zebra
2019-07-03 10:39:23,214 - INFO - service:add_services - adding service to node(n1): OSPFv2
2019-07-03 10:39:23,214 - INFO - service:add_services - adding service to node(n1): OSPFv3
2019-07-03 10:39:23,214 - INFO - service:add_services - adding service to node(n1): IPForward
2019-07-03 10:39:23,214 - INFO - corexml:read_device - reading node id(2) model(router) name(n2)
2019-07-03 10:39:23,214 - INFO - coreemu:add_node - creating node(CoreNode) id(2) name(n2) start(False)
2019-07-03 10:39:23,214 - INFO - service:add_services - setting services for node(n2): ['zebra', 'OSPFv2', 'OSPFv3', 'IPForward']
2019-07-03 10:39:23,214 - INFO - service:add_services - adding service to node(n2): zebra
2019-07-03 10:39:23,214 - INFO - service:add_services - adding service to node(n2): OSPFv2
2019-07-03 10:39:23,214 - INFO - service:add_services - adding service to node(n2): OSPFv3
2019-07-03 10:39:23,214 - INFO - service:add_services - adding service to node(n2): IPForward
2019-07-03 10:39:23,214 - INFO - corexml:read_device - reading node id(3) model(router) name(n3)
2019-07-03 10:39:23,214 - INFO - coreemu:add_node - creating node(CoreNode) id(3) name(n3) start(False)
2019-07-03 10:39:23,214 - INFO - service:add_services - setting services for node(n3): ['zebra', 'OSPFv2', 'OSPFv3', 'IPForward']
2019-07-03 10:39:23,214 - INFO - service:add_services - adding service to node(n3): zebra
2019-07-03 10:39:23,214 - INFO - service:add_services - adding service to node(n3): OSPFv2
2019-07-03 10:39:23,214 - INFO - service:add_services - adding service to node(n3): OSPFv3
2019-07-03 10:39:23,214 - INFO - service:add_services - adding service to node(n3): IPForward
2019-07-03 10:39:23,214 - INFO - corexml:read_links - reading link node_one(2) node_two(3)
2019-07-03 10:39:23,215 - INFO - coreemu:add_link - adding link for peer to peer nodes: n2 - n3
2019-07-03 10:39:23,215 - INFO - coreemu:add_link - adding link from node to network: n2 - 42807
2019-07-03 10:39:23,215 - INFO - coreemu:link_config - configuring link for network(42807): {'loss': None, 'jitter': None, 'netif': <core.netns.vif.VEth object at 0x7f9dede27e50>, 'devname': None, 'delay': None, 'duplicate': None, 'bw': None, 'netif2': None}
2019-07-03 10:39:23,215 - INFO - coreemu:add_link - adding link from network to node: n3 - 42807
2019-07-03 10:39:23,215 - INFO - coreemu:link_config - configuring link for network(42807): {'loss': None, 'jitter': None, 'netif': <core.netns.vif.VEth object at 0x7f9dede273d0>, 'devname': None, 'delay': None, 'duplicate': None, 'bw': None, 'netif2': None}
2019-07-03 10:39:23,215 - INFO - corexml:read_links - reading link node_one(3) node_two(1)
2019-07-03 10:39:23,215 - INFO - coreemu:add_link - adding link for peer to peer nodes: n3 - n1
2019-07-03 10:39:23,215 - INFO - coreemu:add_link - adding link from node to network: n3 - 37879
2019-07-03 10:39:23,215 - INFO - coreemu:link_config - configuring link for network(37879): {'loss': 1.0, 'jitter': None, 'netif': <core.netns.vif.VEth object at 0x7f9dede27510>, 'devname': None, 'delay': None, 'duplicate': None, 'bw': None, 'netif2': None}
2019-07-03 10:39:23,215 - INFO - coreemu:add_link - adding link from network to node: n1 - 37879
2019-07-03 10:39:23,215 - INFO - coreemu:link_config - configuring link for network(37879): {'loss': 1.0, 'jitter': None, 'netif': <core.netns.vif.VEth object at 0x7f9dede27490>, 'devname': None, 'delay': None, 'duplicate': None, 'bw': None, 'netif2': None}
2019-07-03 10:39:23,215 - INFO - corexml:read_links - reading link node_one(1) node_two(2)
2019-07-03 10:39:23,215 - INFO - coreemu:add_link - adding link for peer to peer nodes: n1 - n2
2019-07-03 10:39:23,215 - INFO - coreemu:add_link - adding link from node to network: n1 - 33688
2019-07-03 10:39:23,216 - INFO - coreemu:link_config - configuring link for network(33688): {'loss': None, 'jitter': None, 'netif': <core.netns.vif.VEth object at 0x7f9dede27390>, 'devname': None, 'delay': None, 'duplicate': None, 'bw': None, 'netif2': None}
2019-07-03 10:39:23,216 - INFO - coreemu:add_link - adding link from network to node: n2 - 33688
2019-07-03 10:39:23,216 - INFO - coreemu:link_config - configuring link for network(33688): {'loss': None, 'jitter': None, 'netif': <core.netns.vif.VEth object at 0x7f9dede27310>, 'devname': None, 'delay': None, 'duplicate': None, 'bw': None, 'netif2': None}
2019-07-03 10:39:23,216 - ERROR - corehandlers:handle_message - Thread-12: exception while handling message: CoreEventMessage <msgtype = EVENT, flags = 0x0 <>>
  TYPE: 11
  NAME: /home/user/.core/configs/test.xml
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/core/corehandlers.py", line 490, in handle_message
    replies = message_handler(message)
  File "/usr/local/lib/python2.7/dist-packages/core/corehandlers.py", line 1474, in handle_event_message
    self.send_objects()
  File "/usr/local/lib/python2.7/dist-packages/core/corehandlers.py", line 1696, in send_objects
    self.session.broadcast_link(link_data)
  File "/usr/local/lib/python2.7/dist-packages/core/session.py", line 196, in broadcast_link
    handler(link_data)
  File "/usr/local/lib/python2.7/dist-packages/core/corehandlers.py", line 356, in handle_broadcast_link
    (LinkTlvs.OPAQUE, link_data.opaque)
  File "/usr/local/lib/python2.7/dist-packages/core/misc/structutils.py", line 44, in pack_values
    data += clazz.pack(tlv_type.value, value)
  File "/usr/local/lib/python2.7/dist-packages/core/api/coreapi.py", line 399, in pack
    tlv_len, tlv_data = cls.tlv_data_class_map[tlv_type].pack(value)
  File "/usr/local/lib/python2.7/dist-packages/core/api/coreapi.py", line 180, in pack
    raise ValueError("value not a string: %s" % value)
ValueError: value not a string: 1.0
```

**Comment by bharnden** [comment]
Looks like its related to trying to change to deal with loss as an integer, but not accounting for the GUI sending it as a float in string form. Try updating it to just "1" and hopefully this will fix it for you for now. I will try to compensate for this in the next release.

**Comment by emirljuca** [comment]
Okay thanks, I would think then that floats would not work for the next release?

**Comment by bharnden** [comment]
I can look into seeing what is supported by the command, I am not sure offhand. Do you need the fidelity of a loss of partial percents?

**Comment by bharnden** [comment]
Put a change on develop to revert behavior to align with using floats as it did before and avoid this issue, change on develop.
