### ISSUE TITLE
[BUG] Custom Service Crashes on Emulation Start

### ISSUE THREAD

**Issue by GarettFox** [coreemu/core#268]
**Describe the bug**
I created a custom service that just puts a shell script on the node to be used to test average download times from HTTP server nodes, but it crashes every time I start the emulation. I tried putting it in myservices and adding it to the sdn.py script, but both attempts result in the same errors. I also have tried changing or removing the directory the shell script is placed in, but this didn't work either. I also tried changing DLService(CoreService) to DLService(SdnService) in case there was something there that would help it work.

**To Reproduce**
1. Put this code into a service script: (I also haven't removed the default comments in my actual code but I'm guessing that's not the problem)
`
## Custom CORE Service
```python
class DLService(CoreService):
    ### Service Attributes
    name = "DownloadCheck"
    group = "SDN"
    executables = ()
    dependencies = ()
    dirs = ("/sdn")
    configs = ("/sdn/download.sh")
    startup = ("ls /sdn")
    validate = ("sh %s" % configs[0])
    shutdown = ()

    ### On Load
    @classmethod
    def on_load(cls):
        pass

    ### Generate Config
    @classmethod
    def generate_config(cls, node, filename):
        if filename == cls.configs[0]:
            cfg = "#!/bin/sh\n"
            cfg += "x=1\n"
            cfg += "y=0\n"
            cfg += "while [ $x -le $3 ]\n"
            cfg += "do\n"
            cfg += "	z=date +%s%6N\n"
            cfg += "	wget $1/$2.html\n"
            cfg += "	a=date +%s%N; y=$(( a - z ))\n"
            cfg += "	$(( x++ ))\n"
            cfg += "done\n"
            cfg += "b=$(( y / 100 ))\n"
            cfg += "echo \"Average: $b microseconds\"\n"
            return cfg
        else:
            return ""
```
2. Restart core-daemon
3. Open core-gui, select a node, and enable DownloadCheck as a service
4. Run the emulation, and the DownloadCheck service crashes

**Expected behavior**
I expect the service to work without error and create a shell script that can be used to download html files from specified servers and report the average download time.

**Screenshots**
Here's a relevant snippet from my core-daemon.log
```shell
2019-07-04 05:36:44,341 - DEBUG - coreservices:_start - starting service dependency check: DownloadCheck
2019-07-04 05:36:44,342 - DEBUG - coreservices:_visit - visiting service(DownloadCheck): []
2019-07-04 05:36:44,342 - DEBUG - coreservices:_visit - adding service to boot path: DownloadCheck
2019-07-04 05:36:44,342 - DEBUG - coreservices:_start - starting service dependency check: DefaultRoute
2019-07-04 05:36:44,342 - DEBUG - coreservices:_visit - visiting service(DefaultRoute): []
2019-07-04 05:36:44,342 - DEBUG - coreservices:_visit - adding service to boot path: DefaultRoute
2019-07-04 05:36:44,342 - DEBUG - coreservices:_start - starting service dependency check: DefaultRoute
2019-07-04 05:36:44,342 - DEBUG - coreservices:_visit - visiting service(DefaultRoute): []
2019-07-04 05:36:44,342 - INFO - coreservices:_start_boot_paths - booting node services: DownloadCheck
2019-07-04 05:36:44,343 - DEBUG - coreservices:_visit - adding service to boot path: DefaultRoute
2019-07-04 05:36:44,343 - DEBUG - coreservices:_start - starting service dependency check: IPForward
2019-07-04 05:36:44,343 - INFO - coreservices:_start_boot_paths - booting node services: DefaultRoute
2019-07-04 05:36:44,343 - INFO - coreservices:boot_service - starting node(n1) service(DownloadCheck) validation(NON_BLOCKING)
2019-07-04 05:36:44,343 - DEBUG - coreservices:_start - starting service dependency check: HTTP
2019-07-04 05:36:44,343 - DEBUG - coreservices:_visit - visiting service(IPForward): []
2019-07-04 05:36:44,343 - DEBUG - coreservices:_visit - adding service to boot path: IPForward
2019-07-04 05:36:44,343 - DEBUG - coreservices:_visit - visiting service(HTTP): []
2019-07-04 05:36:44,343 - INFO - coreservices:boot_service - starting node(n1) service(DefaultRoute) validation(NON_BLOCKING)
2019-07-04 05:36:44,343 - ERROR - coreservices:_start_boot_paths - exception booting service: DownloadCheck
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/core/services/coreservices.py", line 451, in _start_boot_paths
    self.boot_service(node, service)
  File "/usr/lib/python3/dist-packages/core/services/coreservices.py", line 471, in boot_service
    node.privatedir(directory)
  File "/usr/lib/python3/dist-packages/core/nodes/base.py", line 605, in privatedir
    os.mkdir(hostpath)
FileExistsError: [Errno 17] File exists: '/tmp/pycore.44435/n1.conf/'
2019-07-04 05:36:44,343 - DEBUG - coreservices:_start - starting service dependency check: StaticRoute
2019-07-04 05:36:44,343 - DEBUG - coreservices:_visit - adding service to boot path: HTTP
2019-07-04 05:36:44,343 - INFO - coreservices:create_service_files - node(n1) service(DefaultRoute) creating config files
2019-07-04 05:36:44,344 - DEBUG - coreservices:_visit - visiting service(StaticRoute): []
2019-07-04 05:36:44,344 - DEBUG - coreservices:_start - starting service dependency check: SSH
2019-07-04 05:36:44,344 - DEBUG - coreservices:create_service_files - generating service config: defaultroute.sh
2019-07-04 05:36:44,344 - DEBUG - coreservices:_visit - adding service to boot path: StaticRoute
2019-07-04 05:36:44,344 - DEBUG - coreservices:_visit - visiting service(SSH): []
2019-07-04 05:36:44,344 - INFO - coreservices:_start_boot_paths - booting node services: IPForward
2019-07-04 05:36:44,344 - DEBUG - coreservices:_visit - adding service to boot path: SSH
2019-07-04 05:36:44,344 - INFO - coreservices:boot_service - starting node(n3) service(IPForward) validation(NON_BLOCKING)
2019-07-04 05:36:44,345 - INFO - coreservices:create_service_files - node(n3) service(IPForward) creating config files
2019-07-04 05:36:44,344 - INFO - coreservices:_start_boot_paths - booting node services: StaticRoute
2019-07-04 05:36:44,344 - INFO - base:nodefile - node(n1) added file: /tmp/pycore.44435/n1.conf/defaultroute.sh; mode: 0644
2019-07-04 05:36:44,345 - INFO - coreservices:_start_boot_paths - booting node services: DefaultRoute
2019-07-04 05:36:44,345 - DEBUG - coreservices:create_service_files - generating service config: ipforward.sh
2019-07-04 05:36:44,345 - INFO - coreservices:_start_boot_paths - booting node services: HTTP
2019-07-04 05:36:44,345 - INFO - coreservices:_start_boot_paths - booting node services: SSH
2019-07-04 05:36:44,345 - INFO - coreservices:boot_service - starting node(n3) service(StaticRoute) validation(NON_BLOCKING)
2019-07-04 05:36:44,345 - INFO - utils:split_args - split args: sh defaultroute.sh - <class 'str'>
2019-07-04 05:36:44,345 - INFO - coreservices:boot_service - starting node(n2) service(DefaultRoute) validation(NON_BLOCKING)
2019-07-04 05:36:44,345 - INFO - coreservices:boot_service - starting node(n2) service(HTTP) validation(NON_BLOCKING)
2019-07-04 05:36:44,345 - INFO - coreservices:boot_service - starting node(n2) service(SSH) validation(NON_BLOCKING)
2019-07-04 05:36:44,345 - INFO - base:nodefile - node(n3) added file: /tmp/pycore.44435/n3.conf/ipforward.sh; mode: 0644
2019-07-04 05:36:44,345 - INFO - coreservices:create_service_files - node(n3) service(StaticRoute) creating config files
2019-07-04 05:36:44,345 - INFO - utils:split_args - splitting args
2019-07-04 05:36:44,345 - INFO - coreservices:create_service_files - node(n2) service(DefaultRoute) creating config files
2019-07-04 05:36:44,345 - INFO - base:mount - node(n2) mounting: /tmp/pycore.44435/n2.conf/etc.apache2 at /etc/apache2
2019-07-04 05:36:44,345 - INFO - base:mount - node(n2) mounting: /tmp/pycore.44435/n2.conf/etc.ssh at /etc/ssh
2019-07-04 05:36:44,345 - DEBUG - coreservices:create_service_files - generating service config: staticroute.sh
2019-07-04 05:36:44,345 - INFO - utils:split_args - split args: sh ipforward.sh - <class 'str'>
2019-07-04 05:36:44,346 - INFO - client:cmd - cmd wait(False): ['/usr/local/bin/vcmd', '-c', '/tmp/pycore.44435/n1', '--', 'sh', 'defaultroute.sh']
2019-07-04 05:36:44,346 - DEBUG - coreservices:create_service_files - generating service config: defaultroute.sh
2019-07-04 05:36:44,346 - INFO - utils:split_args - split args: ['/bin/sh', '-c', 'mkdir -p "/etc/apache2" && /usr/bin/mount -n --bind "/tmp/pycore.44435/n2.conf/etc.apache2" "/etc/apache2"'] - <class 'list'>
2019-07-04 05:36:44,346 - INFO - utils:split_args - split args: ['/bin/sh', '-c', 'mkdir -p "/etc/ssh" && /usr/bin/mount -n --bind "/tmp/pycore.44435/n2.conf/etc.ssh" "/etc/ssh"'] - <class 'list'>
2019-07-04 05:36:44,346 - INFO - utils:split_args - splitting args
2019-07-04 05:36:44,346 - INFO - base:nodefile - node(n3) added file: /tmp/pycore.44435/n3.conf/staticroute.sh; mode: 0644
2019-07-04 05:36:44,348 - INFO - client:popen - popen: ['/usr/local/bin/vcmd', '-c', '/tmp/pycore.44435/n2', '--', '/bin/sh', '-c', 'mkdir -p "/etc/apache2" && /usr/bin/mount -n --bind "/tmp/pycore.44435/n2.conf/etc.apache2" "/etc/apache2"']
2019-07-04 05:36:44,349 - INFO - client:popen - popen: ['/usr/local/bin/vcmd', '-c', '/tmp/pycore.44435/n2', '--', '/bin/sh', '-c', 'mkdir -p "/etc/ssh" && /usr/bin/mount -n --bind "/tmp/pycore.44435/n2.conf/etc.ssh" "/etc/ssh"']
2019-07-04 05:36:44,349 - INFO - base:nodefile - node(n2) added file: /tmp/pycore.44435/n2.conf/defaultroute.sh; mode: 0644
2019-07-04 05:36:44,349 - INFO - client:cmd - cmd wait(False): ['/usr/local/bin/vcmd', '-c', '/tmp/pycore.44435/n3', '--', 'sh', 'ipforward.sh']
2019-07-04 05:36:44,351 - INFO - utils:split_args - split args: sh staticroute.sh - <class 'str'>
2019-07-04 05:36:44,353 - INFO - coreservices:validate_service - validating node(n1) service(DefaultRoute)
2019-07-04 05:36:44,353 - INFO - utils:split_args - split args: sh defaultroute.sh - <class 'str'>
2019-07-04 05:36:44,355 - INFO - utils:split_args - splitting args
2019-07-04 05:36:44,359 - INFO - utils:split_args - splitting args
2019-07-04 05:36:44,361 - INFO - client:cmd - cmd wait(False): ['/usr/local/bin/vcmd', '-c', '/tmp/pycore.44435/n3', '--', 'sh', 'staticroute.sh']
2019-07-04 05:36:44,361 - INFO - base:mount - node(n2) mounting: /tmp/pycore.44435/n2.conf/var.run.apache2 at /var/run/apache2
2019-07-04 05:36:44,361 - INFO - client:cmd - cmd wait(False): ['/usr/local/bin/vcmd', '-c', '/tmp/pycore.44435/n2', '--', 'sh', 'defaultroute.sh']
2019-07-04 05:36:44,362 - INFO - utils:split_args - split args: ['/bin/sh', '-c', 'mkdir -p "/var/run/apache2" && /usr/bin/mount -n --bind "/tmp/pycore.44435/n2.conf/var.run.apache2" "/var/run/apache2"'] - <class 'list'>
2019-07-04 05:36:44,362 - INFO - client:popen - popen: ['/usr/local/bin/vcmd', '-c', '/tmp/pycore.44435/n2', '--', '/bin/sh', '-c', 'mkdir -p "/var/run/apache2" && /usr/bin/mount -n --bind "/tmp/pycore.44435/n2.conf/var.run.apache2" "/var/run/apache2"']
2019-07-04 05:36:44,365 - INFO - coreservices:validate_service - validating node(n3) service(IPForward)
2019-07-04 05:36:44,368 - INFO - base:mount - node(n2) mounting: /tmp/pycore.44435/n2.conf/var.run.sshd at /var/run/sshd
2019-07-04 05:36:44,371 - INFO - utils:split_args - split args: ['/bin/sh', '-c', 'mkdir -p "/var/run/sshd" && /usr/bin/mount -n --bind "/tmp/pycore.44435/n2.conf/var.run.sshd" "/var/run/sshd"'] - <class 'list'>
2019-07-04 05:36:44,373 - INFO - client:popen - popen: ['/usr/local/bin/vcmd', '-c', '/tmp/pycore.44435/n2', '--', '/bin/sh', '-c', 'mkdir -p "/var/run/sshd" && /usr/bin/mount -n --bind "/tmp/pycore.44435/n2.conf/var.run.sshd" "/var/run/sshd"']
2019-07-04 05:36:44,373 - INFO - coreservices:validate_service - validating node(n2) service(DefaultRoute)
2019-07-04 05:36:44,375 - INFO - coreservices:validate_service - validating node(n3) service(StaticRoute)
2019-07-04 05:36:44,377 - INFO - base:mount - node(n2) mounting: /tmp/pycore.44435/n2.conf/var.log.apache2 at /var/log/apache2
2019-07-04 05:36:44,377 - INFO - utils:split_args - split args: ['/bin/sh', '-c', 'mkdir -p "/var/log/apache2" && /usr/bin/mount -n --bind "/tmp/pycore.44435/n2.conf/var.log.apache2" "/var/log/apache2"'] - <class 'list'>
2019-07-04 05:36:44,377 - INFO - client:popen - popen: ['/usr/local/bin/vcmd', '-c', '/tmp/pycore.44435/n2', '--', '/bin/sh', '-c', 'mkdir -p "/var/log/apache2" && /usr/bin/mount -n --bind "/tmp/pycore.44435/n2.conf/var.log.apache2" "/var/log/apache2"']
2019-07-04 05:36:44,383 - INFO - coreservices:create_service_files - node(n2) service(SSH) creating config files
2019-07-04 05:36:44,383 - DEBUG - coreservices:create_service_files - generating service config: startsshd.sh
2019-07-04 05:36:44,383 - INFO - base:nodefile - node(n2) added file: /tmp/pycore.44435/n2.conf/startsshd.sh; mode: 0644
2019-07-04 05:36:44,383 - DEBUG - coreservices:create_service_files - generating service config: /etc/ssh/sshd_config
2019-07-04 05:36:44,383 - INFO - base:nodefile - node(n2) added file: /tmp/pycore.44435/n2.conf/etc.ssh/sshd_config; mode: 0644
2019-07-04 05:36:44,383 - INFO - utils:split_args - split args: sh startsshd.sh - <class 'str'>
2019-07-04 05:36:44,383 - INFO - utils:split_args - splitting args
2019-07-04 05:36:44,383 - INFO - client:cmd - cmd wait(False): ['/usr/local/bin/vcmd', '-c', '/tmp/pycore.44435/n2', '--', 'sh', 'startsshd.sh']
2019-07-04 05:36:44,388 - INFO - base:mount - node(n2) mounting: /tmp/pycore.44435/n2.conf/run.lock at /run/lock
2019-07-04 05:36:44,388 - INFO - utils:split_args - split args: ['/bin/sh', '-c', 'mkdir -p "/run/lock" && /usr/bin/mount -n --bind "/tmp/pycore.44435/n2.conf/run.lock" "/run/lock"'] - <class 'list'>
2019-07-04 05:36:44,388 - INFO - client:popen - popen: ['/usr/local/bin/vcmd', '-c', '/tmp/pycore.44435/n2', '--', '/bin/sh', '-c', 'mkdir -p "/run/lock" && /usr/bin/mount -n --bind "/tmp/pycore.44435/n2.conf/run.lock" "/run/lock"']
2019-07-04 05:36:44,391 - INFO - coreservices:validate_service - validating node(n2) service(SSH)
2019-07-04 05:36:44,397 - INFO - base:mount - node(n2) mounting: /tmp/pycore.44435/n2.conf/var.lock.apache2 at /var/lock/apache2
2019-07-04 05:36:44,397 - INFO - utils:split_args - split args: ['/bin/sh', '-c', 'mkdir -p "/var/lock/apache2" && /usr/bin/mount -n --bind "/tmp/pycore.44435/n2.conf/var.lock.apache2" "/var/lock/apache2"'] - <class 'list'>
2019-07-04 05:36:44,397 - INFO - client:popen - popen: ['/usr/local/bin/vcmd', '-c', '/tmp/pycore.44435/n2', '--', '/bin/sh', '-c', 'mkdir -p "/var/lock/apache2" && /usr/bin/mount -n --bind "/tmp/pycore.44435/n2.conf/var.lock.apache2" "/var/lock/apache2"']
2019-07-04 05:36:44,404 - INFO - base:mount - node(n2) mounting: /tmp/pycore.44435/n2.conf/var.www at /var/www
2019-07-04 05:36:44,404 - INFO - utils:split_args - split args: ['/bin/sh', '-c', 'mkdir -p "/var/www" && /usr/bin/mount -n --bind "/tmp/pycore.44435/n2.conf/var.www" "/var/www"'] - <class 'list'>
2019-07-04 05:36:44,405 - INFO - client:popen - popen: ['/usr/local/bin/vcmd', '-c', '/tmp/pycore.44435/n2', '--', '/bin/sh', '-c', 'mkdir -p "/var/www" && /usr/bin/mount -n --bind "/tmp/pycore.44435/n2.conf/var.www" "/var/www"']
2019-07-04 05:36:44,412 - INFO - coreservices:create_service_files - node(n2) service(HTTP) creating config files
2019-07-04 05:36:44,412 - DEBUG - coreservices:create_service_files - generating service config: /etc/apache2/apache2.conf
2019-07-04 05:36:44,412 - INFO - utils:split_args - split args: ['a2query', '-v'] - <class 'list'>
2019-07-04 05:36:44,412 - DEBUG - utils:cmd_output - command: ['a2query', '-v']
2019-07-04 05:36:44,744 - INFO - base:nodefile - node(n2) added file: /tmp/pycore.44435/n2.conf/etc.apache2/apache2.conf; mode: 0644
2019-07-04 05:36:44,744 - DEBUG - coreservices:create_service_files - generating service config: /etc/apache2/envvars
2019-07-04 05:36:44,744 - INFO - base:nodefile - node(n2) added file: /tmp/pycore.44435/n2.conf/etc.apache2/envvars; mode: 0644
2019-07-04 05:36:44,745 - DEBUG - coreservices:create_service_files - generating service config: /var/www/index.html
2019-07-04 05:36:44,745 - INFO - base:nodefile - node(n2) added file: /tmp/pycore.44435/n2.conf/var.www/index.html; mode: 0644
2019-07-04 05:36:44,745 - DEBUG - coreservices:create_service_files - generating service config: /var/www/1k.html
2019-07-04 05:36:44,746 - INFO - base:nodefile - node(n2) added file: /tmp/pycore.44435/n2.conf/var.www/1k.html; mode: 0644
2019-07-04 05:36:44,746 - INFO - utils:split_args - split args: chown www-data /var/lock/apache2 - <class 'str'>
2019-07-04 05:36:44,746 - INFO - utils:split_args - splitting args
2019-07-04 05:36:44,746 - INFO - client:cmd - cmd wait(False): ['/usr/local/bin/vcmd', '-c', '/tmp/pycore.44435/n2', '--', 'chown', 'www-data', '/var/lock/apache2']
2019-07-04 05:36:44,753 - INFO - utils:split_args - split args: apache2ctl start - <class 'str'>
2019-07-04 05:36:44,753 - INFO - utils:split_args - splitting args
2019-07-04 05:36:44,754 - INFO - client:cmd - cmd wait(False): ['/usr/local/bin/vcmd', '-c', '/tmp/pycore.44435/n2', '--', 'apache2ctl', 'start']
2019-07-04 05:36:44,761 - INFO - coreservices:validate_service - validating node(n2) service(HTTP)
2019-07-04 05:36:44,761 - DEBUG - coreservices:validate_service - validating service(HTTP) using: pidof apache2
2019-07-04 05:36:44,762 - INFO - utils:split_args - split args: pidof apache2 - <class 'str'>
2019-07-04 05:36:44,762 - INFO - utils:split_args - splitting args
2019-07-04 05:36:44,762 - INFO - client:popen - popen: ['/usr/local/bin/vcmd', '-c', '/tmp/pycore.44435/n2', '--', 'pidof', 'apache2']
2019-07-04 05:36:44,941 - ERROR - corehandlers:handle_message - Thread-5: exception while handling message: CoreEventMessage <msgtype = EVENT, flags = 0x0 <>>
  TYPE: 3
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/core/api/tlv/corehandlers.py", line 499, in handle_message
    replies = message_handler(message)
  File "/usr/lib/python3/dist-packages/core/api/tlv/corehandlers.py", line 1454, in handle_event_message
    self.session.instantiate()
  File "/usr/lib/python3/dist-packages/core/emulator/session.py", line 1229, in instantiate
    self.boot_nodes()
  File "/usr/lib/python3/dist-packages/core/emulator/session.py", line 1360, in boot_nodes
    result.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3/dist-packages/core/services/coreservices.py", line 438, in boot_services
    result.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3/dist-packages/core/services/coreservices.py", line 451, in _start_boot_paths
    self.boot_service(node, service)
  File "/usr/lib/python3/dist-packages/core/services/coreservices.py", line 471, in boot_service
    node.privatedir(directory)
  File "/usr/lib/python3/dist-packages/core/nodes/base.py", line 605, in privatedir
    os.mkdir(hostpath)
FileExistsError: [Errno 17] File exists: '/tmp/pycore.44435/n1.conf/'
```

**Desktop (please complete the following information):**
 - OS: Kali GNU/Linux Rolling
 - CORE Version 5.3
 - EMANE Version 1.2.3

**Additional context**
I'm guessing not, but is it possible there's still some lingering issues from [my previous post?](https://github.com/coreemu/core/issues/264)

**Comment by bharnden** [comment]
Your issue for now is related to the code not being what you think it is.

Below what looks like tuples are not, single items with parenthesis are the item itself, you need to add a "," to make them tuples.
```python
dirs = ("/sdn")
configs = ("/sdn/download.sh")
startup = ("ls /sdn")
validate = ("sh %s" % configs[0])
```

You would want the following:
```python
dirs = ("/sdn",)
configs = ("/sdn/download.sh",)
startup = ("ls /sdn",)
validate = ("sh %s" % configs[0],)
```

**Comment by bharnden** [comment]
Feel free to let me know if there were any other issues.
