### ISSUE TITLE
[BUG] Session start fails through missing permission

### ISSUE THREAD

**Issue by jonashoechst** [coreemu/core#315]
When starting a session with just one in CORE 5.5.2, it fails for me. 

To reproduce, one can use our docker container, `docker pull maciresearch/core_worker:0.5.1` ([Source](https://github.com/umr-ds/maci-docker-compose/blob/master/core_worker/Dockerfile)). The container provides a Gui, when a valid DISPLAY variable is supplied, e.g. by configuring an open X server or forwarding through ssh.

Create and start a session with one node. The output or core-daemon is at `/var/log/core-daemon.log`: 

```
2019-11-11 15:24:23,452 - INFO - core-daemon:banner - CORE daemon v.5.5.2 started Mon Nov 11 15:24:23 2019
2019-11-11 15:24:23,462 - INFO - core-daemon:cored - CORE TLV API TCP/UDP listening on: localhost:4038
2019-11-11 15:24:24,218 - INFO - emanemanager:emane_check - emane is not installed
2019-11-11 15:24:24,219 - INFO - coreemu:create_session - created session: 45787
2019-11-11 15:24:24,219 - INFO - session:set_state - changing session(45787) to state DEFINITION_STATE
2019-11-11 15:24:24,220 - INFO - corehandlers:register - GUI has connected to session 45787 at Mon Nov 11 15:24:24 2019
2019-11-11 15:24:37,474 - INFO - session:set_state - session(45787) is already in state: DEFINITION_STATE, skipping change
2019-11-11 15:24:37,474 - INFO - session:set_state - changing session(45787) to state CONFIGURATION_STATE
2019-11-11 15:24:37,475 - INFO - corehandlers:handle_config_location - location configured: (0.0, 0.0, 0.0) = (47.5791667, -122.132322, 2.0) scale=150.0
2019-11-11 15:24:37,475 - INFO - corehandlers:handle_config_location - location configured: UTM((10, 'T'), 565249.2879168927, 5269892.809170721, 2.0)
2019-11-11 15:24:37,513 - INFO - session:add_node - creating node(CoreNode) id(1) name(n1) start(True)
2019-11-11 15:24:37,518 - ERROR - corehandlers:handle_message - Thread-3: exception while handling message: CoreNodeMessage <msgtype = NODE, flags = 0x11 <ADD | STRING>>
  NUMBER: 1
  TYPE: 0
  NAME: n1
  MODEL: PC
  X_POSITION: 106
  Y_POSITION: 152
Traceback (most recent call last):
  File "/usr/lib/python3.6/dist-packages/core/api/tlv/corehandlers.py", line 552, in handle_message
    replies = message_handler(message)
  File "/usr/lib/python3.6/dist-packages/core/api/tlv/corehandlers.py", line 743, in handle_node_message
    node = self.session.add_node(node_type, node_id, node_options)
  File "/usr/lib/python3.6/dist-packages/core/emulator/session.py", line 686, in add_node
    node = self.create_node(cls=node_class, _id=_id, name=name, start=start)
  File "/usr/lib/python3.6/dist-packages/core/emulator/session.py", line 1343, in create_node
    node = cls(self, *args, **kwargs)
  File "/usr/lib/python3.6/dist-packages/core/nodes/base.py", line 472, in __init__
    self.startup()
  File "/usr/lib/python3.6/dist-packages/core/nodes/base.py", line 518, in startup
    output = utils.check_cmd(vnoded, env=env)
  File "/usr/lib/python3.6/dist-packages/core/utils.py", line 272, in check_cmd
    raise CoreCommandError(status, args, stdout)
core.errors.CoreCommandError: Command(['/usr/bin/vnoded', '-v', '-c', '/tmp/pycore.45787/n1', '-l', '/tmp/pycore.45787/n1.log', '-p', '/tmp/pycore.45787/n1.pid', '-C', '/tmp/pycore.45787/n1.conf']), Status(1):
b'vnoded[42]: 15:24:37.518185 vnoded[vnode_server.c:291]: nsfork() failed: Operation not permitted\nvnoded[42]: 15:24:37.518367 main[vnoded_main.c:222]: vnoded() failed\n'
2019-11-11 15:24:37,522 - INFO - session:set_state - changing session(45787) to state INSTANTIATION_STATE
2019-11-11 15:24:37,636 - INFO - session:set_state - changing session(45787) to state RUNTIME_STATE
```

Ubuntu 18.04, CORE 5.5.2.

**Comment by jonashoechst** [comment]
Oh, nevermind, we missed the --privileged flag. Sorry.
