### ISSUE TITLE
How to adjust lastest(2.4) version of Apache to make it work with CORE?

### ISSUE THREAD

**Issue by Ca11back** [coreemu/core#408]
The new version of Apache have changed the dir structure and conf files.
When I set up a new host with HTTP in CORE GUI,there also will be an error about that node failed validation.
I had try to add new file name which correspond to it in my computer in HTTP Service dialog and remove the old files. But it won't work. And when I try to save this as xml,all of my changes about these new files will lost. These files will recover to origial path like "/var/www/index.html" instead of "/srv/http/index.html" which I have added.
I know this may be a naive question of most of you.
But this is a huge hurdle for me.
I have googled it and search some docs.
But I really can't fix this.
Could any one give me a help,even a releative hyperlink will be help.
Thanks!!

**Comment by Ca11back** [comment]
This is my first time of using CORE and Apache,It's really hard.

**Comment by Ca11back** [comment]
I had set start cmd to "apachectl start/stop",validation cmd to "pidof httpd"and add 3 files: index.html. httpd.conf and envvars.
But this dosen't work,I still get the error:
```
2020-03-20 18:30:57,594 - ERROR - coreservices:_start_boot_paths - exception booting service: HTTP
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/core/services/coreservices.py", line 490, in _start_boot_paths
    self.boot_service(node, service)
  File "/usr/lib/python3.8/site-packages/core/services/coreservices.py", line 555, in boot_service
    raise ServiceBootError(
core.services.coreservices.ServiceBootError: node(n1) service(HTTP) failed validation
2020-03-20 18:30:57,596 - ERROR - utils:threadpool - thread pool exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/core/utils.py", line 424, in threadpool
    result = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/core/services/coreservices.py", line 490, in _start_boot_paths
    self.boot_service(node, service)
  File "/usr/lib/python3.8/site-packages/core/services/coreservices.py", line 555, in boot_service
    raise ServiceBootError(
core.services.coreservices.ServiceBootError: node(n1) service(HTTP) failed validation

```

**Comment by bharnden** [comment]
The node you are trying to run this one, will typically still have all the files and be in the state of failure.

You should then be able to open a terminal on the node and manually run the commands you are trying to see what is causing you issue. Once you figure out your problems, then you can create a custom service for this new case to help make repeating the process easier.

http://coreemu.github.io/core/services.html#creating-new-services

**Comment by Ca11back** [comment]
> The node you are trying to run this on, will typically still have all the files and be in the state of failure.
> 
> You should then be able to open a terminal on the node and manually run the commands you are trying to see what is causing your issue. Once you figure out your problems, then you can create a custom service for this new case to help make repeating the process easier.
> 
> http://coreemu.github.io/core/services.html#creating-new-services

Thank you very much sir! Thanks for your reply!
I have changed my sever to lighttpd, and follow your instruction to create a lighttpd.py.
This is partial code of it:

```
dirs = (
    	'/run/lock',
    	'/etc/lighttpd',
    	'/var/run/lighttpd',
        '/var/log/lighttpd',
        '/srv/http'
    )
    configs = (
    	'/etc/lighttpd/lighttpd.conf',
    	'/srv/http/index.html'
    )
    startup = ('lighttpd -f /etc/lighttpd/lighttpd.conf')
    validate = ('pidof lighttpd')
    shutdown = ('killall lighttpd')

    def generate_config(cls, node, filename):
        cfg = "# auto-generated by Lighttpd (lighttpd.py)\n"
        with open(filename,'r') as f:
        	cfg += f.read()
        return cfg
```

But I still got the same error:
```
2020-03-21 11:10:57,824 - ERROR - coreservices:_start_boot_paths - exception booting service: Lighttpd
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/core/services/coreservices.py", line 490, in _start_boot_paths
    self.boot_service(node, service)
  File "/usr/lib/python3.8/site-packages/core/services/coreservices.py", line 555, in boot_service
    raise ServiceBootError(
core.services.coreservices.ServiceBootError: node(n1) service(Lighttpd) failed validation
2020-03-21 11:10:57,825 - ERROR - utils:threadpool - thread pool exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/core/utils.py", line 424, in threadpool
    result = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/core/services/coreservices.py", line 490, in _start_boot_paths
    self.boot_service(node, service)
  File "/usr/lib/python3.8/site-packages/core/services/coreservices.py", line 555, in boot_service
    raise ServiceBootError(
core.services.coreservices.ServiceBootError: node(n1) service(Lighttpd) failed validation
2020-03-21 11:10:57,826 - ERROR - utils:threadpool - thread pool exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/core/utils.py", line 424, in threadpool
    result = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/core/emulator/session.py", line 1636, in boot_node
    self.services.boot_services(node)
  File "/usr/lib/python3.8/site-packages/core/services/coreservices.py", line 472, in boot_services
    raise ServiceBootError(*exceptions)
core.services.coreservices.ServiceBootError: node(n1) service(Lighttpd) failed validation
```
Then I try to use the terminal of my host to perform startup,validate and shutdown command manually. And there is no error,and it works fun. I also used lynx to check it.
So I was quite curious about this. How should I locate the error,sir?

**Comment by bharnden** [comment]
This method is responsible for actually creating the file, not reading it.

```python
def generate_config(cls, node, filename):
        cfg = "# auto-generated by Lighttpd (lighttpd.py)\n"
        cfg += "commands to run etc\n"
        return cfg
```

**Comment by Ca11back** [comment]
> This method is responsible for actually creating the file, not reading it.
> 
> ```python
> def generate_config(cls, node, filename):
>         cfg = "# auto-generated by Lighttpd (lighttpd.py)\n"
>         cfg += "commands to run etc\n"
>         return cfg
> ```

Well,sir,by this I mean made it to copy the files from my computer(default config file).
And it works fun.I think problem may due to other part.
Thanks for reply!

**Comment by bharnden** [comment]
Ah I see, yes that could work too, I was assuming you though it would create them for you.

**Comment by Ca11back** [comment]
> Ah I see, yes that could work too, I was assuming you thought it would create them for you.

I known where is the problem.
So stupid am I!
```
validate = ('pidof lighttpd')
shutdown = ('killall lighttpd')
```
should be
```
validate = ('pidof lighttpd',)
shutdown = ('killall lighttpd',)
```
So stupid am I!!!
