### ISSUE TITLE
[BUG] Importing .xml topologies in Python3 API not working 

### ISSUE THREAD

**Issue by juslesan** [coreemu/core#410]
**Describe the bug**
Hello, I have been facing this bug when trying to update the CORE from version 5.2 with Python2 API to Core 6+ versions with Python3.

Whenever I try to import a .xml topology and run session.instantiate() in the python3 API in any 6+ COREEMU version the execution fails when starting the services of the node.

The topologies that I'm using work with the python2 API in CORE 5.2, and they also work with the CORE 6.2 gui. Exporting topologies from the Python3 API seems to work as I was able to open them in the GUI. I can also see the services of the nodes in the xml file.

**To Reproduce**

Use the Python3 API with these lines with an exported .xml topology:

session = coreemu.create_session()
session.open_xml("topology.xml", False)
session.instantiate()

**Expected behavior**
The services of the nodes in the saved xml topologies should get booted properly on session.instantiate().

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - CORE Version 6.0+

**Additional context**

Some error logs from core

ERROR:root:exception booting service: zebra
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/core/services/coreservices.py", line 490, in _start_boot_paths
    self.boot_service(node, service)
  File "/usr/local/lib/python3.6/dist-packages/core/services/coreservices.py", line 514, in boot_service
    node.privatedir(directory)
  File "/usr/local/lib/python3.6/dist-packages/core/nodes/base.py", line 667, in privatedir
    self.nodedir, os.path.normpath(path).strip("/").replace("/", ".")
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

2020-03-26 14:58:00,589 - root - ERROR - thread pool exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/core/utils.py", line 424, in threadpool
    result = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/core/emulator/session.py", line 1636, in boot_node
    self.services.boot_services(node)
  File "/usr/local/lib/python3.6/dist-packages/core/services/coreservices.py", line 472, in boot_services
    raise ServiceBootError(*exceptions)
core.services.coreservices.ServiceBootError: expected str, bytes or os.PathLike object, not NoneType

Similar logs get repeated for all node services on session.instantiate()

**Comment by bharnden** [comment]
Thanks, will look into this. 

A quick thing to try may be using True with open_xml, I believe that gets to a starting scenario, as the boolean flag was added to support how the GUI initializes things in a different way.

**Comment by bharnden** [comment]
Looking into it briefly, you should be able to use the same code and set open_xml to start. Which would accomplish what you are trying in that small snippet.

If you there is a reason you don't want to start the opened XML right away and then try to modify it after the fact, it is currently a pain and not really ideal. There could be efforts to help improve that, but it's not planned at the moment.

```python
session = coreemu.create_session()
session.open_xml("topology.xml", start=True)
```

**Comment by juslesan** [comment]
Thanks, this seems to fix the issue with the services. I have been doing some modifications on the session before starting so this might lead in to some new issues.
