### ISSUE TITLE
[BUG] Basic WiFi Model: core.services.coreservices.ServiceBootError: index out range for address range size!

### ISSUE THREAD

**Issue by gh0st42** [coreemu/core#427]
**Describe the bug**
When using the basic WiFi model nodes in `core-gui` are not able to *see* each other. The same setup worked flawless in older versions of core (<=6.0.0).

**To Reproduce**
1. Add two PC nodes
2. Add WiFi (no EMANE)
3. Link WiFi to all routers
4. Start scenario
5. Drag nodes right next to each other
6. See error

**Expected behavior**
Both nodes should be able to *see* each other if dragged near each other. No green line ever comes up and `ping` does not work.

**Log Output**

```
2020-04-11 14:46:21,299 - ERROR - utils:threadpool - thread pool exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/core/utils.py", line 424, in threadpool
    result = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/core/emulator/session.py", line 1636, in boot_node
    self.services.boot_services(node)
  File "/usr/local/lib/python3.6/dist-packages/core/services/coreservices.py", line 472, in boot_services
    raise ServiceBootError(*exceptions)
core.services.coreservices.ServiceBootError: index out range for address range size!
```

Only service activated is `DefaultRoute`. Deactivating it does not make a difference.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version: 6.1 and 6.2
 - EMANE Version: Basic WiFi model
 
**Additional context**
Without WiFi but with a manual, fixed connection, everything works as expected.

The whole bug can be reproduced in a simple docker container.
Here the docker build file:
```Dockerfile
FROM ubuntu:18.04
LABEL Description="Docker image for core network emulator"


ENV DEBIAN_FRONTEND noninteractive

# development tools
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    iputils-ping \
    net-tools \
    vim \
    nano \
    mtr \
    tmux \
    iperf \
    git \
    && apt-get clean

# CORE dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    wget \
    bridge-utils \
    ebtables \
    kmod \
    iproute2 \
    libev4 \
    python3 \
    python3-setuptools \
    python3-pip \
    python3-future \
    python3-tk \
    python3-netaddr \
    python3-mako \
    quagga \
    tcl \
    tk \
    libtk-img \
    lxterminal \
    ethtool \
    psmisc \
    && apt-get clean

# install ssh deamon
RUN apt-get update \
    && apt-get install -y --no-install-recommends ssh \
    && apt-get clean

WORKDIR /root
RUN wget https://raw.githubusercontent.com/coreemu/core/master/daemon/requirements.txt && \
    python3 -m pip install -r requirements.txt && \
    rm requirements.txt

# CORE
RUN wget --quiet https://github.com/coreemu/core/releases/download/release-6.2.0/core_6.2.0_amd64.deb \
    && dpkg -i core_6.2.0_amd64.deb \
    && rm core_6.2.0_amd64.deb
# CORE
#RUN wget --quiet https://github.com/coreemu/core/releases/download/release-6.0.0/core_6.0.0_amd64.deb \
#&& dpkg -i core_6.0.0_amd64.deb \
#&& rm core_6.0.0_amd64.deb

WORKDIR /root
RUN git clone https://github.com/gh0st42/core-helpers &&\
    cd core-helpers && ./install-symlinks.sh

# enable sshd
RUN mkdir /var/run/sshd &&  sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#X11UseLocalhost yes/X11UseLocalhost no/' /etc/ssh/sshd_config && \
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV PASSWORD "netsim"
RUN echo "root:$PASSWORD" | chpasswd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22

# ADD extra /extra
VOLUME /shared

COPY entryPoint.sh /root/entryPoint.sh
ENTRYPOINT "/root/entryPoint.sh"
```

The `entryPoint.sh` file contents:
```bash
#!/bin/bash

systemctl enable ssh
service ssh start
core-daemon > /var/log/core-daemon.log 2>&1 &

core-gui
```
By tweaking the core version in the Dockerfile one can easily install version 6.0 and see it working again.

Build it using `docker build -t coreemu6 .`

And run with something similar to the following:
```
xhost + 127.0.0.1

docker run -it --rm \
    --name coreemu6 \
    -p 2000:22 \
    -v shared:/root/shared \
    --cap-add=NET_ADMIN \
    --cap-add=SYS_ADMIN \
    -e DISPLAY=host.docker.internal:0 \
    --privileged \
    coreemu6
```

**Comment by bharnden** [comment]
The default route service was updated in relation to this and should likely work on the develop branch. I believe this to be the case offhand.

**Comment by gh0st42** [comment]
But why does this then happen even if I deactivate the default route service?

**Comment by bharnden** [comment]
There is a separate issue where when all services are disabled, it defaults back to using the default services, which in your case is the defaultroute service.

There some work to fix that still and handle all different cases.

**Comment by bharnden** [comment]
noting the default route error as fixed on develop and in next release
