### ISSUE TITLE
[BUG] Builtin example wlan.py produces multiple errors

### ISSUE THREAD

**Issue by lemon-lyman** [coreemu/core#491]
**Describe the bug**
Running the [builtin wlan.py](https://github.com/coreemu/core/blob/master/daemon/examples/python/wlan.py) produces two errors.

1.
The line:
`address = prefixes.ip4_address(first_node)`
produces this error
```
Traceback (most recent call last):
  File "wlan.py", line 58, in <module>
    main()
  File "wlan.py", line 47, in main
    address = prefixes.ip4_address(first_node)
  File "/usr/local/lib/python3.8/dist-packages/core/emulator/emudata.py", line 145, in ip4_address
    return str(self.ip4[node_id])
  File "/usr/local/lib/python3.8/dist-packages/netaddr/ip/__init__.py", line 722, in __getitem__
    index = int(index)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'CoreNode'
```
This is a simple fix. I change first_node to first_node.id so the line is now

`address = prefixes.ip4_address(first_node.id)`

2.

Once that change is made, the script seems to mostly run as intended. However, two errors appear in the output. These errors do not prevent the script from completing and the script appears to successfully complete the ping test between the two nodes. Here is the logging output with the two errors:

```
INFO:root:using EMANE: 1.2.6
INFO:root:created session: 1
INFO:root:changing session(1) to state CONFIGURATION_STATE
INFO:root:creating node(WlanNode) id(100) name(WlanNode100) start(True)
INFO:root:creating node(CoreNode) id(1) name(CoreNode1) start(True)
INFO:root:using default services for node(CoreNode1) type(mdr)
INFO:root:setting services for node(CoreNode1): ('zebra', 'OSPFv3MDR', 'IPForward')
INFO:root:setting node config services: []
INFO:root:adding link from node to network: CoreNode1 - WlanNode100
INFO:root:creating node(CoreNode) id(2) name(CoreNode2) start(True)
INFO:root:using default services for node(CoreNode2) type(mdr)
INFO:root:setting services for node(CoreNode2): ('zebra', 'OSPFv3MDR', 'IPForward')
INFO:root:setting node config services: []
INFO:root:adding link from node to network: CoreNode2 - WlanNode100
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/core/nodes/network.py", line 159, in updateloop
    self.ebcommit(wlan)
  File "/usr/local/lib/python3.8/dist-packages/core/nodes/network.py", line 172, in ebcommit
    wlan.host_cmd(args)
  File "/usr/local/lib/python3.8/dist-packages/core/nodes/network.py", line 316, in host_cmd
    output = utils.cmd(args, env, cwd, wait, shell)
  File "/usr/local/lib/python3.8/dist-packages/core/utils.py", line 226, in cmd
    raise CoreCommandError(status, args, stdout, stderr)
core.errors.CoreCommandError: Command(['/usr/sbin/ebtables', '--atomic-file', '/tmp/pycore.ebtables.atomic', '--atomic-save']), Status(2):
stdout: 
stderr: ebtables v1.8.4 (nf_tables): Unknown argument: '--atomic-save'
Try `ebtables -h' or 'ebtables --help' for more information.
INFO:root:booting node(CoreNode1): ['zebra', 'OSPFv3MDR', 'IPForward']
INFO:root:booting node(CoreNode2): ['zebra', 'OSPFv3MDR', 'IPForward']
INFO:root:booting node(CoreNode1) services: zebra -> OSPFv3MDR
INFO:root:starting node(CoreNode1) service(zebra) validation(NON_BLOCKING)
INFO:root:booting node(CoreNode1) services: IPForward
INFO:root:starting node(CoreNode1) service(IPForward) validation(NON_BLOCKING)
INFO:root:booting node(CoreNode2) services: zebra -> OSPFv3MDR
INFO:root:starting node(CoreNode2) service(zebra) validation(NON_BLOCKING)
INFO:root:booting node(CoreNode2) services: IPForward
INFO:root:starting node(CoreNode2) service(IPForward) validation(NON_BLOCKING)
INFO:root:starting node(CoreNode1) service(OSPFv3MDR) validation(NON_BLOCKING)
INFO:root:starting node(CoreNode2) service(OSPFv3MDR) validation(NON_BLOCKING)
INFO:root:changing session(1) to state RUNTIME_STATE
INFO:root:node CoreNode2 pinging 10.83.0.1
INFO:root:PING 10.83.0.1 (10.83.0.1) 56(84) bytes of data.
64 bytes from 10.83.0.1: icmp_seq=1 ttl=64 time=20.7 ms
64 bytes from 10.83.0.1: icmp_seq=2 ttl=64 time=10.9 ms
64 bytes from 10.83.0.1: icmp_seq=3 ttl=64 time=10.4 ms

--- 10.83.0.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 10.438/14.012/20.736/4.757 ms
INFO:root:shutting down all sessions
INFO:root:session(1) shutting down
INFO:root:changing session(1) to state DATACOLLECT_STATE
INFO:root:changing session(1) to state SHUTDOWN_STATE
ERROR:root:error during shutdown
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/core/nodes/network.py", line 349, in shutdown
    ebtablescmds(self.host_cmd, cmds)
  File "/usr/local/lib/python3.8/dist-packages/core/nodes/network.py", line 252, in ebtablescmds
    call(args)
  File "/usr/local/lib/python3.8/dist-packages/core/nodes/network.py", line 316, in host_cmd
    output = utils.cmd(args, env, cwd, wait, shell)
  File "/usr/local/lib/python3.8/dist-packages/core/utils.py", line 226, in cmd
    raise CoreCommandError(status, args, stdout, stderr)
core.errors.CoreCommandError: Command(['/usr/sbin/ebtables', '-D', 'FORWARD', '--logical-in', 'b.100.1', '-j', 'b.100.1']), Status(1):
stdout: 
stderr: ebtables: Bad rule (does a matching rule exist in that chain?)

```

**To Reproduce**
Run [core/daemon/examples/python/wlan.py](https://github.com/coreemu/core/blob/master/daemon/examples/python/wlan.py)

**Expected behavior**
Run w/out errors and successfully run a ping test between two mdr nodes.

**Desktop:**
 - OS: Ubuntu 20.04 within a VirtualBox on Mac
 - CORE Version 6.5.0 (I think. I took this from the GUI > about. How should I check this from the command line?)
 - EMANE Version 1.2.6
 - Python Version 3.8.2

I didn't find any complaints about this script so I assume this is an error on my end. Any help would be greatly appreciated!

**Comment by bharnden** [comment]
Thanks for part 1, will double check that and the other examples.

Part 2 is due to a change by recent OS distributions dropping ebtables support for nftables. Some provide ebtables by way of a wrapped nftables versions, but it is not directly compatible with prior versions, as you see. This was planned to helped be dealt with in the next releases automated install script and documentation pointing this out.

One command you can run at least on Ubuntu 20 is the following:
```shell
sudo update-alternatives --set ebtables /usr/sbin/ebtables-legacy
```

**Comment by lemon-lyman** [comment]
Thanks for the response!

Part 2: After running that command, I no longer raise the errors. Thanks for the help.

**Comment by bharnden** [comment]
The issue for the example was caught and fixed on develop, thanks for helping point it out though!
