### ISSUE TITLE
[BUG] Installing into RHEL 8

### ISSUE THREAD

**Issue by esend7881** [coreemu/core#617]
**Describe the bug**
I'm working on installed CORE onto my RHEL 8.4 machine and facing issues.

**To Reproduce**
1. Clone 7.5.2
2. Run ./install.sh
3. Error:

```
checking for tc... no

Stderr:

configure: error: Could not locate tc (from iproute package).
```

**Expected behavior**
The program tc/iproute would be found.

Besides this, I developed an RPM for quagga (from https://github.com/USNavalResearchLaboratory/ospf-mdr) that took a bit of work. I'm not sure if quagga has anything to do with my issues, but I thought I would attach it here just in case.

[rpmbuild.zip](https://github.com/coreemu/core/files/7334164/rpmbuild.zip)

**Desktop (please complete the following information):**
 - OS: RHEL 8.4
 - CORE Version 7.5.2
 - EMANE Version [e.g. 1.2.4] N/A

**Additional context**
My goal is to install CORE from an RPM without any building. I know RPMs are [supplied here](https://github.com/coreemu/core/releases/download/release-7.5.2/core_distributed_7.5.2_x86_64.rpm), however after installing that RPM, I don't see `core-...` executables available so I'm actually not sure what that RPM is doing.

I am using RHEL 8.4 development version but I could use CentOS 8 just as easily. In the end, if there is any SOF or issue article that discusses in finer detail out to install CORE 7.x on RHEL 8/CentOS 8, that may solve my issues.

**Comment by bharnden** [comment]
There is no RPM to install from currently, the packages are only for convenience of setting up distributed machines. The previous response should resolve the `tc` part.

**Comment by esend7881** [comment]
Yes - this got me through the `./install.sh` script! Now I am trying to properly set up my `PYTHONPATH` variable so my Python environment can find Python EMU (note I am coming from the CORE 6.x world). Its after 10PM my time so I will do a deeper dive tomorrow, maybe the explanation for transitioning from v6 to v7 is in the documentation.

**Comment by esend7881** [comment]
@bharnden - I tried that but it didn't help. I'm thinking it has more to do with the `PYTHONPATH` based on this error:

```
Traceback (most recent call last):
  File "1_multiple_links_test.py", line 12, in <module>
    import rmbn_test
  File "test.py", line 18, in <module>
    from core.errors import CoreCommandError
ModuleNotFoundError: No module named 'core'
```

It's not finding the Python module named `core`. With Core v6 and RHEL7, I was able to set the Python path to `/usr/local/lib/python3.6/dist-packages` but that isn't working on v7/RHEL8
