### ISSUE TITLE
[BUG] basic WLAN not working anymore

### ISSUE THREAD

**Issue by gh0st42** [coreemu/core#742]
**Describe the bug**
Basic WLAN starts but does not connect nodes.
The same setup with the new WIRELESS does work on the same machine.

**To Reproduce**
1. add two PC
2. add a WLAN node
3. connect PCs to WLAN (see screenshot below)
4. start simulation
5. see error in screenshots

**Expected behavior**

The same setup on the same machine worked with previous coreemu versions and the nodes should be able to connect as in WIRELESS it also works.

**Screenshots**

<img width="259" alt="Screenshot 2023-01-20 at 22 27 38" src="https://user-images.githubusercontent.com/1264131/213808408-7cf0f958-1b6c-4659-b9d4-e5f8b16e2baf.png">

```
2023-01-20 21:25:17,834 - INFO - daemon:banner - CORE daemon v.9.0.1 started Fri Jan 20 21:25:17 2023
2023-01-20 21:25:18,359 - INFO - coreemu:_load_emane - using emane: 1.4.1
2023-01-20 21:25:18,390 - INFO - server:listen - CORE gRPC API listening on: 0.0.0.0:50051
2023-01-20 21:25:18,774 - INFO - coreemu:create_session - created session: 1
2023-01-20 21:26:09,541 - INFO - session:set_state - changing session(1) to state CONFIGURATION_STATE
2023-01-20 21:26:09,541 - INFO - base:__init__ - setting node config services: ['DefaultRoute']
2023-01-20 21:26:09,541 - INFO - session:create_node - created node(CoreNode) id(1) name(n1) start(True)
2023-01-20 21:26:09,543 - INFO - base:__init__ - setting node config services: ['DefaultRoute']
2023-01-20 21:26:09,543 - INFO - session:create_node - created node(CoreNode) id(2) name(n2) start(True)
2023-01-20 21:26:09,544 - INFO - session:create_node - created node(WlanNode) id(3) name(wlan3) start(True)
2023-01-20 21:26:09,879 - INFO - links:add - adding link from node(n1:eth0) to node(wlan3:None)
2023-01-20 21:26:09,879 - INFO - links:add - adding link from node(n2:eth0) to node(wlan3:None)
2023-01-20 21:26:09,880 - INFO - session:set_state - changing session(1) to state INSTANTIATION_STATE
2023-01-20 21:26:09,880 - INFO - session:boot_node - booting node(n1): []
2023-01-20 21:26:09,880 - INFO - base:start - node(n1) service(DefaultRoute) starting...
2023-01-20 21:26:09,884 - INFO - session:boot_node - booting node(n2): []
2023-01-20 21:26:09,884 - INFO - base:start - node(n2) service(DefaultRoute) starting...
2023-01-20 21:26:09,888 - ERROR - mobility:startup - mobility startup error
Traceback (most recent call last):
  File "/opt/core/daemon/core/location/mobility.py", line 45, in get_mobility_node
    return session.get_node(node_id, WlanNode)
  File "/opt/core/daemon/core/emulator/session.py", line 947, in get_node
    raise CoreError(f"node class({actual}) is not expected({expected})")
core.errors.CoreError: node class(CoreNode) is not expected(WlanNode)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/core/daemon/core/location/mobility.py", line 130, in startup
    node = get_mobility_node(self.session, node_id)
  File "/opt/core/daemon/core/location/mobility.py", line 47, in get_mobility_node
    return session.get_node(node_id, EmaneNet)
  File "/opt/core/daemon/core/emulator/session.py", line 947, in get_node
    raise CoreError(f"node class({actual}) is not expected({expected})")
core.errors.CoreError: node class(CoreNode) is not expected(EmaneNet)
2023-01-20 21:26:09,888 - WARNING - mobility:startup - skipping mobility configuration for unknown node: 1
2023-01-20 21:26:09,889 - INFO - session:set_state - changing session(1) to state RUNTIME_STATE
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - CORE Version 9.0.1

**Comment by bharnden** [comment]
I followed your steps exactly and see no error. It appears you are using a mobility script?

**Comment by gh0st42** [comment]
No mobility configured - at least no ns2 movemen, the xml still wraps the WLAN configuration in a mobility configuration.
all this is after a fresh start (ubuntu docker image, build from source, checkout 9.0.1 - not the deb version)

<img width="808" alt="Screenshot 2023-01-20 at 23 42 58" src="https://user-images.githubusercontent.com/1264131/213818236-9f81ab86-a812-49c9-ba0c-1297dfa2e555.png">

saving the scenario produces the following xml file:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<scenario name="/tmp/tmpgv9d4b6e">
  <networks>
    <network id="3" name="wlan3" icon="" canvas="1" type="WIRELESS_LAN">
      <position x="97.0" y="206.0" lat="47.577293908981034" lon="-122.13101717001157" alt="2.0"/>
    </network>
  </networks>
  <devices>
    <device id="1" name="n1" icon="" canvas="1" type="PC" class="" image="">
      <position x="55.0" y="86.0" lat="47.578384695787456" lon="-122.13158310864058" alt="2.0"/>
      <configservices>
        <service name="DefaultRoute"/>
      </configservices>
    </device>
    <device id="2" name="n2" icon="" canvas="1" type="PC" class="" image="">
      <position x="179.0" y="71.0" lat="47.578521042540466" lon="-122.12991224221211" alt="2.0"/>
      <configservices>
        <service name="DefaultRoute"/>
      </configservices>
    </device>
  </devices>
  <links>
    <link node1="1" node2="3">
      <iface1 id="0" name="eth0" ip4="10.0.0.20" ip4_mask="24" ip6="2001::14" ip6_mask="128"/>
    </link>
    <link node1="2" node2="3">
      <iface1 id="0" name="eth0" ip4="10.0.0.21" ip4_mask="24" ip6="2001::15" ip6_mask="128"/>
    </link>
  </links>
  <mobility_configurations>
    <mobility_configuration node="1" model="basic_range">
      <configuration name="range" value="275"/>
      <configuration name="bandwidth" value="54000000"/>
      <configuration name="jitter" value="0"/>
      <configuration name="delay" value="5000"/>
      <configuration name="error" value="0.0"/>
      <configuration name="promiscuous" value="0"/>
    </mobility_configuration>
  </mobility_configurations>
  <configservice_configurations>
    <service name="DefaultRoute" node="1"/>
    <service name="DefaultRoute" node="2"/>
  </configservice_configurations>
  <session_origin lat="47.579166412353516" lon="-122.13232421875" alt="2.0" scale="150.0"/>
  <session_options>
    <configuration name="controlnet" value=""/>
    <configuration name="controlnet0" value=""/>
    <configuration name="controlnet1" value=""/>
    <configuration name="controlnet2" value=""/>
    <configuration name="controlnet3" value=""/>
    <configuration name="controlnet_updown_script" value=""/>
    <configuration name="enablerj45" value="1"/>
    <configuration name="preservedir" value="0"/>
    <configuration name="enablesdt" value="0"/>
    <configuration name="sdturl" value="tcp://127.0.0.1:50000/"/>
    <configuration name="ovs" value="0"/>
    <configuration name="platform_id_start" value="1"/>
    <configuration name="nem_id_start" value="1"/>
    <configuration name="link_enabled" value="1"/>
    <configuration name="loss_threshold" value="30"/>
    <configuration name="link_interval" value="1"/>
    <configuration name="link_timeout" value="4"/>
    <configuration name="mtu" value="0"/>
  </session_options>
  <session_metadata>
    <configuration name="shapes" value="[]"/>
    <configuration name="edges" value="[]"/>
    <configuration name="hidden" value="[]"/>
    <configuration name="canvas" value="{&quot;gridlines&quot;: true, &quot;canvases&quot;: [{&quot;id&quot;: 1, &quot;wallpaper&quot;: null, &quot;wallpaper_style&quot;: 1, &quot;fit_image&quot;: false, &quot;dimensions&quot;: [1000, 750]}]}"/>
  </session_metadata>
  <default_services>
    <node type="mdr">
      <service name="zebra"/>
      <service name="OSPFv3MDR"/>
      <service name="IPForward"/>
    </node>
    <node type="PC">
      <service name="DefaultRoute"/>
    </node>
    <node type="prouter"/>
    <node type="router">
      <service name="zebra"/>
      <service name="OSPFv2"/>
      <service name="OSPFv3"/>
      <service name="IPForward"/>
    </node>
    <node type="host">
      <service name="DefaultRoute"/>
      <service name="SSH"/>
    </node>
  </default_services>
</scenario>
```

looking at the XML i realize that the generated config references the wrong node id:
`<mobility_configuration node="1" model="basic_range">`
the actual WLAN node id is `3`. 
if i change the XML code to the correct node id everything works.
Somehow the node IDs generated for the mobility/wifi config don't match the actual topology.

**Comment by bharnden** [comment]
So you are saying manually following your steps and saving to XML will give the bad mobility? I will check this out, thanks.

**Comment by gh0st42** [comment]
yes, freshly started core 9.0.1, starting the gui and directly following my initial steps and saving the topology produces this xml 

but only with WLAN, the new WIRELESS with loss range works (but doesn’t support mobility) and EMANE also works

**Comment by bharnden** [comment]
I tried repeating this exact process with a freshly started `core-daemon` and did not get this case.

Maybe you can retry from absolute scratch and see how/if you can recreate it? If I can as well, it help me look into it. Thanks!

**Comment by gh0st42** [comment]
here, is the docker file I used to build the image (more or less based on your official ones but tweaked to work on arm64 as well as amd64 platforms:

```Dockerfile
# syntax=docker/dockerfile:1
ARG ARCH=
FROM ${ARCH}ubuntu:22.04
LABEL Description="CORE Docker Ubuntu Image"

# define variables
ARG PREFIX=/usr/local
#ARG BRANCH=master
ARG BRANCH=release-9.0.1

# define environment
ENV DEBIAN_FRONTEND=noninteractive

# install basic dependencies
RUN apt-get update && \
  apt-get install -y git sudo wget tzdata python3 python3-pip python3-venv && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# install core
WORKDIR /opt
RUN git clone https://github.com/coreemu/core
WORKDIR /opt/core
RUN git checkout ${BRANCH}
#RUN NO_SYSTEM=1 ./setup.sh
RUN ./setup.sh
RUN apt-get update && . /root/.bashrc && inv install -v -p ${PREFIX} && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
ENV PATH "$PATH:/opt/core/venv/bin"

# install emane
#RUN apt-get install -y libpcap-dev libpcre3-dev libprotobuf-dev libxml2-dev protobuf-compiler uuid-dev && \
RUN apt-get update && apt-get install -y libpcap-dev libpcre3-dev libxml2-dev uuid-dev unzip && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /root

# install emane
RUN apt-get update && apt-get install -y libpcap-dev libpcre3-dev libprotobuf-dev libxml2-dev protobuf-compiler unzip uuid-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
WORKDIR /opt
RUN git clone https://github.com/adjacentlink/emane.git
RUN cd emane && \
  ./autogen.sh && \
  ./configure --prefix=/usr && \
  make -j$(nproc)  && \
  make install
RUN ARCH1=$(uname -m | sed -e s/arm64/aarch_64/ | sed -e s/aarch64/aarch_64/) && wget https://github.com/protocolbuffers/protobuf/releases/download/v3.19.6/protoc-3.19.6-linux-$ARCH1.zip && \
  mkdir protoc && \
  unzip protoc-3.19.6-linux-$ARCH1.zip -d protoc
RUN PATH=/opt/protoc/bin:$PATH && \
  cd emane/src/python && \
  make clean && \
  make
RUN /opt/core/venv/bin/python -m pip install emane/src/python

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

RUN mkdir -p /root/.core/myservices && mkdir -p /root/.coregui/custom_services
RUN sed -i 's/grpcaddress = localhost/grpcaddress = 0.0.0.0/g' /etc/core/core.conf

EXPOSE 22
EXPOSE 50051

VOLUME /shared

COPY entrypoint.sh /root/entrypoint.sh
ENTRYPOINT "/root/entrypoint.sh"
```

and the `entrypoint.sh`:
```bash
#!/bin/bash

core-daemon > /var/log/core-daemon.log 2>&1 &

sleep 1

core-gui
```

running everything on ubuntu:
```bash
docker build -t c9 .
xhost +local:root
docker run -it --rm \
    --name c9 \
    --cap-add=NET_ADMIN \
    --cap-add=SYS_ADMIN \
    -e DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
    --privileged \
    c9
```

core-gui should open up automatically and then I perform the steps from the initial bug report.
the host is running ubuntu 22.04 (on arm64 which should not really influence the node ID mapping of the wifi config :))

**Comment by gh0st42** [comment]
also, switching to master does not fix the problem.
the strange thing is that the other WIRELESS network type just works, so it does not look like a general problem with the OS or dependencies

**Comment by bharnden** [comment]
Without knowing just yet, maybe something to do with the Docker setup and using that. It is odd.

I am only testing locally within the context of a VM at the moment, no Docker involved.

**Comment by gh0st42** [comment]
just to be sure, I just tested this on an x86_64 machine (still within docker) and had the same issue that the WLAN mobility config in the xml is linked to the wrong node ID. so it is not an issue of the arch which sometimes pull in different dependencies.

**Comment by bharnden** [comment]
Also to check on the order you do things. Do you design the network and then save or do you design the network, run the network, and then save?

**Comment by gh0st42** [comment]
I tried both, does not make a difference.
Another weird thing is that if I add multiple WLAN networks with nodes attached only one mobility conf is generated in the XML and depending on the creation order of nodes it sometimes points to the valid WLAN node but most of the time to one of the regular nodes.
Past versions did create one mobility section for each configured WLAN.

I just tried my native (non-docker) install of v8.1.0 here, everything works as expected.
Using the release tgz of v8.1.0 in docker (on the same machines) also works as expected.

**Comment by bharnden** [comment]
I'm sorry, I forgot this was addressed already and why I didn't see it. This issue has been fixed, but on develop for the next bugfix release etc

**Comment by gh0st42** [comment]
`develop` branch seems to work again.
