### ISSUE TITLE
stderr: RTNETLINK answers: File exists

### ISSUE THREAD

**Issue by schlom** [coreemu/core#750]
![Screenshot 2023-02-05 185459](https://user-images.githubusercontent.com/1479794/216836522-547eb80c-db03-4946-a324-562e574ca636.png)

**Comment by schlom** [comment]
Try to run a docker image in core. Core-daemon reports:
`2023-02-05 18:52:01,255 - DEBUG - utils:cmd - command cwd(None) wait(True): ip link add name beth1.0.1 type veth peer name veth1.0.1

2023-02-05 18:52:01,257 - ERROR - utils:threadpool - thread pool exception

Traceback (most recent call last):

  File "/home/emu/Downloads/core/daemon/core/utils.py", line 543, in threadpool

    result = future.result()

  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result

    return self.__get_result()

  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result

    raise self._exception

  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/home/emu/Downloads/core/daemon/core/emulator/session.py", line 286, in add_link

    iface1, iface2 = self._add_wired_link(

  File "/home/emu/Downloads/core/daemon/core/emulator/session.py", line 360, in _add_wired_link

    iface1 = node1.create_iface(iface1_data, options)

  File "/home/emu/Downloads/core/daemon/core/nodes/base.py", line 302, in create_iface

    iface.startup()

  File "/home/emu/Downloads/core/daemon/core/nodes/interface.py", line 163, in startup

    self.net_client.create_veth(self.localname, self.name)

  File "/home/emu/Downloads/core/daemon/core/nodes/netclient.py", line 200, in create_veth

    self.run(f"{IP} link add name {name} type veth peer name {peer}")

  File "/home/emu/Downloads/core/daemon/core/nodes/interface.py", line 153, in host_cmd

    return utils.cmd(args, env, cwd, wait, shell)

  File "/home/emu/Downloads/core/daemon/core/utils.py", line 243, in cmd

    raise CoreCommandError(status, input_args, stdout, stderr)

core.errors.CoreCommandError: command(ip link add name beth1.0.1 type veth peer name veth1.0.1), status(2):

stdout: 

stderr: RTNETLINK answers: File exists

`
Any hints?

**Comment by schlom** [comment]
When starting the docker image with core-gui the core-daemon reports:
![Screenshot 2023-02-05 185459](https://user-images.githubusercontent.com/1479794/216836607-c218ae86-d8a3-42b4-935b-f848d77ee12c.png)

**Comment by bharnden** [comment]
That typically indicates the interface already existing, potentially from a prior failed run.

You can try `sudo core-cleanup` to help remove any lingering devices and try again.

**Comment by jhonzy0928** [comment]
I've encountered the same errors, and usually they can be fixed by restarting the service or machine.

**Comment by bharnden** [comment]
The LXD/LXC efforts were done quite a bit ago and is probably the least used. Poking at it now, it appears to first be an issue with the fact that the default profile for an LXC container will create an `eth0`, so this results in the error you are seeing.

You can modify the profile to remove that aspect and fix that issue, but something about how things are done in context of LXC still does not take addressing properly like normal CORE nodes or Docker based nodes.

I would say for now to avoid the LXD/LXC and use Docker, if you need an image based container for your node. Otherwise the current state of LXC does not seem to be in a good spot.
