### ISSUE TITLE
[BUG] Configservice PCAP

### ISSUE THREAD

**Issue by schrc3b6** [coreemu/core#802]
**Describe the bug**
When adding the utility pcap service to a component (Router, Docker or PC) the following error is shown:

```
2023-07-13 14:42:17,078 - INFO - coreclient:start_session - start session(1) definition(True), result: True
2023-07-13 14:42:17,099 - ERROR - app:show_grpc_exception - app grpc exception
  Traceback (most recent call last):
      File "/opt/core/venv/lib/python3.9/site-packages/core/gui/dialogs/configserviceconfig.py", line 97, in load
           self.rendered = self.core.get_config_service_rendered(
     File "/opt/core/venv/lib/python3.9/site-packages/core/gui/coreclient.py", line 753, in get_config_service_rendered
         return self.client.get_config_service_rendered(self.session.id, node_id, name)
     File "/opt/core/venv/lib/python3.9/site-packages/core/api/grpc/client.py", line 997, in get_config_service_rendered
        response = self.stub.GetConfigServiceRendered(request)
    File "/opt/core/venv/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
             return _end_unary_response_blocking(state, call, False, None)
    File "/opt/core/venv/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
             raise _InactiveRpcError(state)
               grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
              status = StatusCode.UNKNOWN
          details = "Exception calling application: node(n4) service(pcap) file(pcap.sh)

  Traceback (most recent call last):
      File "/opt/core/venv/lib/python3.9/site-packages/core/configservice/base.py", line 471, in render_template
        return self._render(template, data)
      File "/opt/core/venv/lib/python3.9/site-packages/core/configservice/base.py", line 439, in _render
         return template.render_unicode(
      File "/opt/core/venv/lib/python3.9/site-packages/mako/template.py", line 444, in render_unicode
             return runtime._render(
      File "/opt/core/venv/lib/python3.9/site-packages/mako/runtime.py", line 874, in _render
                 _render_context(
      File "/opt/core/venv/lib/python3.9/site-packages/mako/runtime.py", line 916, in _render_context
              _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
       File "/opt/core/venv/lib/python3.9/site-packages/mako/runtime.py", line 943, in _exec_template
              callable_(context, *args, **kwargs)
       File "/opt/core/venv/lib/python3.9/site-packages/core/configservices/utilservices/templates/pcap.sh", line 5, in render_body
          % for ifname in ifnames:
      TypeError: 'Undefined' object is not iterable
         "
              debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:50051 {created_time:"2023-07-13T14:42:17.099077527+02:00", grpc_status:2, grpc_message:"Exception calling application: node(n4) service(pcap) file(pcap.sh)\n\nTraceback (most recent call last):\n  File \"/opt/core/venv/lib/python3.9/site-packages/core/configservice/base.py\", line 471, in render_template\n    return self._render(template, data)\n  File \"/opt/core/venv/lib/python3.9/site-packages/core/configservice/base.py\", line 439, in _render\n    return template.render_unicode(\n  File \"/opt/core/venv/lib/python3.9/site-packages/mako/template.py\", line 444, in render_unicode\n    return runtime._render(\n  File \"/opt/core/venv/lib/python3.9/site-packages/mako/runtime.py\", line 874, in _render\n    _render_context(\n  File \"/opt/core/venv/lib/python3.9/site-packages/mako/runtime.py\", line 916, in _render_context\n    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)\n  File \"/opt/core/venv/lib/python3.9/site-packages/mako/runtime.py\", line 943, in _exec_template\n    callable_(context, *args, **kwargs)\n  File \"/opt/core/venv/lib/python3.9/site-packages/core/configservices/utilservices/templates/pcap.sh\", line 5, in render_body\n    % for ifname in ifnames:\nTypeError: \'Undefined\' object is not iterable\n"}"
```
** Screenshots**

*** Setting ***
![2023-07-13-151208_758x501_scrot](https://github.com/coreemu/core/assets/30413541/807fcbee-7eb3-4034-bd5d-7178deb01a8e)

*** Start ***
![2023-07-13-151232_711x651_scrot](https://github.com/coreemu/core/assets/30413541/43045eec-fef5-48c3-b679-8f42259b4895)
**To Reproduce**
1. Add a Router and 2 PCs
2. Connect them
3. add pcap Service to the Router
4. start or configure

**Expected behavior**
A PCAP File

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - CORE: 9.0.2 installed via deb
 - EMANE: build from source (yesterday)

**Comment by bharnden** [comment]
this was an issue already fixed on develop for next release, thanks for bringing this up though.

I did however update the pcap script to function as expected from testing as well, also a part of the next release.
