### ISSUE TITLE
[BUG] Docker run does not start core-daemon

### ISSUE THREAD

**Issue by CryptoCopter** [coreemu/core#837]
**Describe the bug**
When following the [docker-install guide](https://coreemu.github.io/core/install.html#dockerfile-based-install), the `docker run` command does not actually start the core-daemon. Therefore, the `docker exec`command fails with

```
2023-11-27 14:13:52,828 - INFO - manager:add_canvas - creating canvas(1)
2023-11-27 14:13:52,860 - ERROR - coreclient:setup - core setup error
Traceback (most recent call last):
  File "/opt/core/daemon/core/gui/coreclient.py", line 362, in setup
    core_config = self.client.get_config()
  File "/opt/core/daemon/core/api/grpc/client.py", line 707, in get_config
    response = self.stub.GetConfig(request)
  File "/opt/core/venv/lib/python3.10/site-packages/grpc/_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/core/venv/lib/python3.10/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50051: Failed to connect to remote host: Connection refused"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50051: Failed to connect to remote host: Connection refused {grpc_status:14, created_time:"2023-11-27T14:13:52.860430435+00:00"}"
>
2023-11-27 14:13:52,861 - ERROR - app:show_grpc_exception - app grpc exception
Traceback (most recent call last):
  File "/opt/core/daemon/core/gui/coreclient.py", line 362, in setup
    core_config = self.client.get_config()
  File "/opt/core/daemon/core/api/grpc/client.py", line 707, in get_config
    response = self.stub.GetConfig(request)
  File "/opt/core/venv/lib/python3.10/site-packages/grpc/_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/core/venv/lib/python3.10/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50051: Failed to connect to remote host: Connection refused"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50051: Failed to connect to remote host: Connection refused {grpc_status:14, created_time:"2023-11-27T14:13:52.860430435+00:00"}"
```

Starting the daemon manually from inside the container and connecting works

**To Reproduce**
1. Follow install instructions
2. Run `docker exec -it core core-gui`
3. Get error
4. Run `docker exec -it core bash`
5. Execute core-daemon instide the container
6. Rerun `docker exec -it core core-gui`
7. Now it works

**Expected behavior**
The dockerfile should automaticcally start the core daemon when executing `docker run` so that the next command from the guide works.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - CORE Version 9.0.3
 - EMANE Version 1.5.1

**Comment by bharnden** [comment]
thanks, I'll update the documentation, you can use `--entrypoint` to start it how you like
