### ISSUE TITLE
[BUG]500 node-IndexError: index out range for address range size

### ISSUE THREAD

**Issue by JH-D** [coreemu/core#856]
**Describe the bug**
200 node, ok.
500 node，error. 
gprc.
```
Traceback (most recent call last):
  File "/home/user1/n500.py", line 351, in createLink
    iface = ip_prefixes.create_iface(node, iface_num)
  File "/root/Documents/core/daemon/core/api/grpc/client.py", line 148, in create_iface
    iface_data = self.prefixes.gen_iface(node_id, name, mac)
  File "/root/Documents/core/daemon/core/emulator/data.py", line 324, in gen_iface
    ip4 = self.ip4_address(node_id)
  File "/root/Documents/core/daemon/core/emulator/data.py", line 296, in ip4_address
    return str(self.ip4[node_id])
  File "/opt/core/venv/lib/python3.10/site-packages/netaddr/ip/__init__.py", line 730, in __getitem__
    raise IndexError('index out range for address range size!')
IndexError: index out range for address range size!
```

**To Reproduce**
1. coreemu.create_session()
2. session.add_node
foreach add 500 node
3. iface_helper = client.InterfaceHelper(ip4_prefix=prefix)
4. iface = ip_prefixes.create_iface(node, iface_num)
the node object is the 345th one
5.  See error

**Expected behavior**
No error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Ubuntu 22.04
 - CORE Version: 9.0.3
 - EMANE Version: no

**Additional context**

**Comment by bharnden** [comment]
The prefix class is just a utility helper. It has a prefix that can not assign enough addresses. So it will eventually run out, like in this case. You would have to make it bigger, but that may also not be what you want.
