### ISSUE TITLE
[BUG] Core 9.1.0 encounters a bug when using the default tdma model.

### ISSUE THREAD

**Issue by LongGieGie** [coreemu/core#881]
**Describe the bug**
Core 9.1.0 encounters a bug when using the default tdma model.

Traceback (most recent call last):
  File "/opt/core/venv/lib/python3.10/site-packages/grpc/_server.py", line 494, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/whl/gitrepos/core/daemon/core/api/grpc/server.py", line 322, in StartSession
    boot_exceptions = session.instantiate()
  File "/home/whl/gitrepos/core/daemon/core/emulator/session.py", line 988, in instantiate
    self.set_state(EventTypes.RUNTIME_STATE, send_event=True)
  File "/home/whl/gitrepos/core/daemon/core/emulator/session.py", line 708, in set_state
    self.hook_manager.run_hooks(state, self.directory, self.get_environment())
  File "/home/whl/gitrepos/core/daemon/core/emulator/hooks.py", line 193, in run_hooks
    _run_callback(state, hook)
  File "/home/whl/gitrepos/core/daemon/core/emulator/hooks.py", line 24, in _run_callback
    raise CoreError(
core.errors.CoreError: failure running state(RUNTIME_STATE) hook callback(callable): 'EmaneManager' object has no attribute 'nem_service'

**Screenshots**
![image](https://github.com/coreemu/core/assets/57282447/c0cedaef-1808-4916-a614-661ab8ab25e0)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - CORE Version 9.1.0
 - EMANE Version 1.5.1

**Comment by bharnden** [comment]
thanks, will correct this mistake

**Comment by bharnden** [comment]
Yes, that is the fixed case on `develop`, it just has not been formally released yet. But, you have the right idea.

**Comment by mikedig** [comment]
Ah I didn't realize there was a develop branch, I see it now. Thanks for the clarification.
