### ISSUE TITLE
[BUG]Exception calling application: Error reading SSH protocol banner

### ISSUE THREAD

**Issue by www-uu** [coreemu/core#890]
**Describe the bug**
This exception occur irregularly and frequently.

**To Reproduce**
1. Distributed deployed: 1 master server, 1 distributed server.
2. exception log:
```
Traceback (most recent call last):
  File "/demo/demo.py", line 184, in startSession
    result, exceptions = self.coreemu.start_session(self.session)
  File "/root/Documents/core/daemon/core/api/grpc/client.py", line 249, in start_session
    response = self.stub.StartSession(request)
  File "/opt/core/venv/lib/python3.10/site-packages/grpc/_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/core/venv/lib/python3.10/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: Error reading SSH protocol banner"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Exception calling application: Error reading SSH protocol banner", grpc_status:2, created_time:"2024-08-21T07:39:03.009693668+00:00"}"
>
```

**Expected behavior**
This exception not occur.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - CORE Version [e.g. 9.0.2]

**Additional context**

**Comment by bharnden** [comment]
The current functionality for distributed uses fabric for SSH connections per node, there is a default SSH setting for 10 connections. I would assume you are potentially hitting this limit at times causing issue.

You can either limit the number of nodes/connections to that distributed server or update the SSH configuration to handle more connections.

**Comment by www-uu** [comment]
> The current functionality for distributed uses fabric for SSH connections per node, there is a default SSH setting for 10 connections. I would assume you are potentially hitting this limit at times causing issue.
> 
> You can either limit the number of nodes/connections to that distributed server or update the SSH configuration to handle more connections.

Previously configured and reboot operating system:
```
sed -i 's/#MaxSessions 10/MaxSessions 500000/' /etc/ssh/sshd_config
```


Complete sshd_config:
```
# cat /etc/ssh/sshd_config

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# This sshd was compiled with PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

Include /etc/ssh/sshd_config.d/*.conf

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

#HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
#HostKey /etc/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
#SyslogFacility AUTH
#LogLevel INFO

# Authentication:

#LoginGraceTime 2m
PermitRootLogin without-password
#StrictModes yes
#MaxAuthTries 6
MaxSessions 500000

#PubkeyAuthentication yes

# Expect .ssh/authorized_keys2 to be disregarded by default in future.
#AuthorizedKeysFile     .ssh/authorized_keys .ssh/authorized_keys2

#AuthorizedPrincipalsFile none

#AuthorizedKeysCommand none
#AuthorizedKeysCommandUser nobody

# For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
PasswordAuthentication yes
#PermitEmptyPasswords no

# Change to yes to enable challenge-response passwords (beware issues with
# some PAM modules and threads)
KbdInteractiveAuthentication no

# Kerberos options
#KerberosAuthentication no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes
#KerberosGetAFSToken no

# GSSAPI options
GSSAPIAuthentication no
#GSSAPICleanupCredentials yes
#GSSAPIStrictAcceptorCheck yes
#GSSAPIKeyExchange no

# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the KbdInteractiveAuthentication and
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication via KbdInteractiveAuthentication may bypass
# the setting of "PermitRootLogin without-password".
# If you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and KbdInteractiveAuthentication to 'no'.
UsePAM yes

#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
X11Forwarding yes
#X11DisplayOffset 10
#X11UseLocalhost yes
#PermitTTY yes
PrintMotd no
#PrintLastLog yes
#TCPKeepAlive yes
#PermitUserEnvironment no
#Compression delayed
#ClientAliveInterval 0
#ClientAliveCountMax 3
UseDNS no
#PidFile /run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# Allow client to pass locale environment variables
AcceptEnv *

# override default of no subsystems
Subsystem       sftp    /usr/lib/openssh/sftp-server

# Example of overriding settings on a per-user basis
#Match User anoncvs
#       X11Forwarding no
#       AllowTcpForwarding no
#       PermitTTY no
#       ForceCommand cvs server
```

**Comment by bharnden** [comment]
I have not tried your setup, so it is hard to say what could be going on.

I can only point you to the general setup (https://coreemu.github.io/core/distributed.html) and the note above on upping the max connections.

Otherwise you could try validating manually, that you can actually carry out passwordless SSH connections and use fabric alone in that same way. That would be a good start to narrow down the issue. Probably not much I can say otherwise.
