### ISSUE TITLE
[BUG]Dependent on pyelftools==0.29 current version is 0.31

### ISSUE THREAD

**Issue by tdsnoke** [coreemu/core#894]
**Describe the bug**
core-daemon is dependent on modules in pyelftools-0.29 and is not compatible with pyelftools-0.31 which is the current rev.

**To Reproduce**
Install CORE using instructions from https://coreemu.github.io/core/install_ubuntu.html and tested the installation by trying to run sudo core-daemon in a terminal, Initially the installation had not included the pyelftools library in the installation and I had to manually add it to the venv. Then when trying to run the tool I got an error because of the compatibility issue.
$ sudo core-daemon
2024-10-17 14:40:07,415 - INFO - daemon:banner - CORE daemon v.9.0.3 started Thu Oct 17 14:40:07 2024
2024-10-17 14:40:07,422 - ERROR - utils:load_module - unexpected error during import, skipping: bin.readelf
Traceback (most recent call last):
  File "/opt/core/venv/lib/python3.10/site-packages/core/utils.py", line 361, in load_module
    module = importlib.import_module(import_statement)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/bin/readelf.py", line 29, in <module>
    from elftools.common.py3compat import (
ModuleNotFoundError: No module named 'elftools.common.py3compat'
2024-10-17 14:40:07,930 - INFO - coreemu:_load_emane - using emane: 1.5.1
2024-10-17 14:40:07,977 - INFO - server:listen - CORE gRPC API listening on: localhost:50051

**Expected behavior**
The expected behavior would not include the error, after reverting the version of pyelftools to 0.29
$ sudo core-daemon 
2024-10-17 14:43:24,902 - INFO - daemon:banner - CORE daemon v.9.0.3 started Thu Oct 17 14:43:24 2024
2024-10-17 14:43:25,440 - INFO - coreemu:_load_emane - using emane: 1.5.1
2024-10-17 14:43:25,486 - INFO - server:listen - CORE gRPC API listening on: localhost:50051

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - CORE Version 9.1.0
 - EMANE Version 1.5.1

**Additional context**

**Comment by bharnden** [comment]
That is not a CORE dependency, you are pointing out a dependency of the `importlib` from the standard library, which CORE happens to use.

Likely something else with the python setup on this system.
