### ISSUE TITLE
Exception in service.py

### ISSUE THREAD

**Issue by justas-** [coreemu/core#93]
To reproduce, open the services menu on a host and click to configure MgenActor service.

core-deamon log will be appended with:
Thread-3: exception while handling msg:
CoreConfMessage <msgtype = CORE_API_CONF_MSG, flags = 0x0 <>>
  CORE_TLV_CONF_OPAQUE: service:MgenActor,MGEN_Sink,DefaultRoute,SSH,MgenDc:start_mgen_actor.sh
  CORE_TLV_CONF_NODE: 1
  CORE_TLV_CONF_OBJ: services
  CORE_TLV_CONF_TYPE: 1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/core/coreserver.py", line 494, in handlemsg
    replies = msghandler(msg)
  File "/usr/local/lib/python2.7/dist-packages/core/coreserver.py", line 1224, in handleconfmsg
    replies = self.session.confobj(objname, self.session, msg)
  File "/usr/local/lib/python2.7/dist-packages/core/session.py", line 538, in confobj
    reply = callback(session, msg)
  File "/usr/local/lib/python2.7/dist-packages/core/conf.py", line 44, in configure
    return self.configure_request(msg)
  File "/usr/local/lib/python2.7/dist-packages/core/service.py", line 423, in configure_request
    return self.getservicefile(services, n, servicesstring[2])
  File "/usr/local/lib/python2.7/dist-packages/core/service.py", line 571, in getservicefile
    data = "%s" % (svc.generateconfig(node, filename, services))
TypeError: not enough arguments for format string

I'm running core-deamon v4.8 from the latest (Oct1) svn snapshot.

**Comment by bharnden** [comment]
should be fixed on rel/5.1 branch
